### ISSUE TITLE
本地和线上的效果不一样如何解决？

### ISSUE THREAD

**Issue by pengtaoa** [liuyib/hexo-theme-stun#101]
## I want to create a new issue 

- [] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** 

**Hexo Version:** 

**Platform:** 

**Browser:** 

## Feature Request 

---

**Comment by liuyib** [comment]
@pengtaoa 问题太笼统了，请举例（不限于，截图，代码展示，等等）

**Comment by Flyraty** [comment]
@pengtaoa 可以执行 hexo clean 后，在 hexo d -g 试试

**Comment by jakeywu** [comment]
@liuyib   你好， 我试了一下也出现线上本地不一致的情况。 能帮助看一下吗
本地正常：

![2020-10-14 11-37-25屏幕截图](https://user-images.githubusercontent.com/11456239/95940739-b511af00-0e11-11eb-8c1b-bb0837feabd4.png)

线上： 

https://jakeywu.github.io/

**Comment by liuyib** [comment]
@jakeywu 我看你的线上也正常，应该是浏览器缓存造成的，Ctrl + F5 强制刷新试试

**Comment by jakeywu** [comment]
@liuyib   恩，　确实是缓存造成的。　谢谢
