### ISSUE TITLE
Can't change the image of the header or body

### ISSUE THREAD

**Issue by CodeRainjzw** [liuyib/hexo-theme-stun#103]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** Date in 2020.9.28 the latest (Sorry I don't know how to see the version of stun)

**Hexo Version:** 5.2.0

**Platform:** Windows

**Browser:** Chrome

## Expected behaviour 
I want to change the header and body image.
I follow the steps one by one and I try use a link of picture(https:\\...) or a local location of picture(\images\name.jpg) 
(If I don't add the url of the picture, it is normal)
## Steps to reproduce the behaviour 
![VK6 O)@2A~X{LIB8{4DL)Y3](https://user-images.githubusercontent.com/72017670/94424318-99c16580-01bc-11eb-8b86-594cf3b03731.png)

## Feature Request 

---

**Comment by CodeRainjzw** [comment]
![1Y`WXZ3U$9ALYI0%AU3$0IP](https://user-images.githubusercontent.com/72017670/94424640-210ed900-01bd-11eb-9b97-5017376b9061.png)

**Comment by CodeRainjzw** [comment]
![7BPX32Y1Y X3H3~LU5Y$)JY](https://user-images.githubusercontent.com/72017670/94424657-29671400-01bd-11eb-9cee-3c70a76d6d66.png)
![DJPO7JBT32AM}Y0~$E`VM)M](https://user-images.githubusercontent.com/72017670/94424669-2c620480-01bd-11eb-9606-1d07a18ef0ea.png)
 
I don't know why the actual behaviour doesn't appear, so I resent them again in comment.

**Comment by liuyib** [comment]
@CodeRainjzw 
That's a typical userland error.
This is because when you modify a configuration file, you don't pay attention to Spaces.

```yaml
bg_image:
  enable: true
  url: https://xxxxxx.png
```

After the `url:`, you must add a space!!! I think you should learn the syntax of `yaml`.
