### ISSUE TITLE
如何修改文章链接里面的yoursite.com，就是每个文章的下面个分享链接地址那

### ISSUE THREAD

**Issue by bevishe** [liuyib/hexo-theme-stun#109]
## I want to create a new issue 

- [] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** 

**Hexo Version:** 

**Platform:** 

**Browser:** 

## Feature Request 

---

![Uploading image.png…]()
你好，请问这里的yoursite.com在哪里进行配置修改，在配置文件里面没有找到地方，谢谢了。

**Comment by bevishe** [comment]
![image](https://user-images.githubusercontent.com/38179390/96212540-bd9ced80-0fa9-11eb-975f-2fa4d6dcd899.png

**Comment by bevishe** [comment]
https://bevishe.oss-cn-hangzhou.aliyuncs.com/img/QQ截图20201016121959.jpg

**Comment by liuyib** [comment]
Hexo 的配置文件里面，找 url

> 你哪怕在项目里面用编辑器全局搜索 yoursite.com 也找到这个配置了
