### ISSUE TITLE
主题配置中的 language: zh 无效

### ISSUE THREAD

**Issue by Cettiidae** [liuyib/hexo-theme-stun#11]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:v1.3.1** 

**Platform:Windows** 

**Browser:Chrome** 

## Expected behaviour 

修改主题配置中 language: zh 的字段，博客主题应变为中文。

## Actual behaviour 

博客仍旧为默认的英文。

## Steps to reproduce the behaviour 

安装了以下插件
``
 "hexo": {  
    "version": "3.9.0"  
  },  
  "dependencies": {  
    "hexo": "^3.9.0",  
    "hexo-admin": "^2.3.0",  
    "hexo-all-minifier": "^0.5.3",  
    "hexo-generator-archive": "^0.1.5",  
    "hexo-generator-category": "^0.1.3",  
    "hexo-generator-feed": "^2.0.0",  
    "hexo-generator-index-pin-top": "^0.2.2",  
    "hexo-generator-search": "^2.4.0",  
    "hexo-generator-tag": "^0.2.0",  
    "hexo-pwa": "^0.1.3",  
    "hexo-renderer-ejs": "^0.3.1",  
    "hexo-renderer-marked": "^1.0.1",  
    "hexo-server": "^0.3.3",  
    "hexo-wordcount": "^6.0.1"  
  },
  "devDependencies": {
    "hexo-render-pug": "^2.1.4",  
    "hexo-renderer-stylus": "^0.3.3"  
``
使用 hexo g生成静态页面后，可见主题语言配置并未生效
## Feature Request 

---

**Comment by liuyib** [comment]
你好，主题的配置文件中并没有单独的 `language:` 配置项，有几个 `language:` 是其他配置项的属性。你说的应该是 Hexo 配置文件里的 `language:` 配置项。

如果你的设置不生效的话，你可以尝试执行指令：`hexo clean && hexo s`，清空 Hexo 缓存后，重启服务器试试。

再者，请确保你的主题目录下的 `languages` 目录中有对应的文件。Stun 默认提供的语言文件有两种：`en` 和 `zh-CN`，你可以尝试下 `language: zh-CN` 而不是 `language: zh`。

**Comment by Cettiidae** [comment]
非常感谢您的回复。
起先在主题的配置文件中寻找到的`language:`确实与博客整体语言无关。而某次生成产生的中文页面让我误以为该配置影响了博客的语言。在按照您的说明再次操作后，已无任何问题，再次感谢您的回复！

**Comment by liuyib** [comment]
很开心能帮助到你，也感谢使用 Stun 主题，如果可以的话，能给个 star 就更好了 😄
