### ISSUE TITLE
使用内嵌方式提供关键 JS/CSS 文件

### ISSUE THREAD

**Issue by DDCHlsq** [liuyib/hexo-theme-stun#111]
主题中将部分 JS/CSS 文件内嵌，但是仍有几个 JS/CSS 文件使用了 cdn.jsdelivr.net 链接来提供。

希望有方法能将所有 JS/CSS 文件内嵌以提高/保证网页渲染速度。

**Comment by liuyib** [comment]
@DDCHlsq 所有 JS / CSS 文件内嵌是不现实的，全都内嵌了，HTML 文件体积就变大了，道理不都一样，总体文件体积还是那些，并不是说内嵌了就提高速度了。

代码内不内嵌要看功能实现，并不是想怎么样就怎么样。

另外，使用 cdn.jsdelivr.net 链接并不是你想的那样，会降低加载速度，反而会提高加载速度，这个你如果明白 CDN 就知道原因了。

最后，也感谢你的建议。对这方面，主题能做的优化是：尽量减少第三方 JS 库的使用，比如：移除 jQuery，全用原生 JS。

CSS 文件体积，你不用担心，都是按需引用的。功能不启用，对应的 CSS 代码就不会出现。
