### ISSUE TITLE
安装好启动报错

### ISSUE THREAD

**Issue by Simonhans** [liuyib/hexo-theme-stun#112]
ERROR {
  err: TypeError: C:\Users\mgxx\Desktop\blog\themes\stun\layout\_third-party\search\localsearch.pug:4
      2|   function initSearch() {
      3|     var isXML = true;
    > 4|     var search_path = '!{ config.search.path }';
      5|
      6|     if (!search_path) {
      7|       search_path = 'search.xml';

  Cannot read property 'path' of undefined

**Comment by liuyib** [comment]
@Simonhans 您好，这个是由于之前有人贡献代码时，错误的打开了默认禁用的配置项，目前已修复，见 https://github.com/liuyib/hexo-theme-stun/commit/5f786e77f5b03e350a591098869948f7cb817eb9

你需要将主题的 _config.yml 文件中的 `local_search` 设置为 `false` 即可解决问题。

**Comment by Simonhans** [comment]
好的，谢谢哈，问题已解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liuyib/hexo-theme-stun"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月24日(星期六) 晚上8:03
收件人:&nbsp;"liuyib/hexo-theme-stun"<hexo-theme-stun@noreply.github.com&gt;;
抄送:&nbsp;"五月"<279867532@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [liuyib/hexo-theme-stun] 安装好启动报错 (#112)





 
@Simonhans 您好，这个是由于之前有人贡献代码时，错误的打开了默认禁用的配置项，目前已修复，见 5f786e7
 
你需要将主题的 _config.yml 文件中的 local_search 设置为 false 即可解决问题。
