### ISSUE TITLE
加密https链接生成的标签链接是http结果

### ISSUE THREAD

**Issue by Keen-King** [liuyib/hexo-theme-stun#118]
- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read the documents of [Hexo](https://hexo.io/docs/).
- [x] Yes, I have read the documents of [Stun](https://liuyib.github.io/hexo-theme-stun/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Environment Information 

**Stun Version:** stun版本2.1.1

**Hexo Version:** hexo 版本4.2.1

**Platform:** Windows 10, centos7

**Browser:** Chrome 83

**Node.js and NPM Information:**
v12.15.0
6.13.4

**Package dependencies Information:**
$  npm ls --depth 0
hexo-site@0.0.0 E:\blog
+-- hexo@4.2.1
+-- hexo-abbrlink@2.2.1
+-- hexo-baidu-url-submit@0.0.6
+-- hexo-deployer-git@2.1.0
+-- hexo-generator-archive@1.0.0
+-- hexo-generator-baidu-sitemap@0.1.9
+-- hexo-generator-category@1.0.0
+-- hexo-generator-index@1.0.0
+-- hexo-generator-search@2.4.0
+-- hexo-generator-sitemap@2.0.0
+-- hexo-generator-tag@1.0.0
+-- hexo-helper-live2d@3.1.1
+-- hexo-render-pug@2.1.4
+-- hexo-renderer-ejs@1.0.0
+-- hexo-renderer-markdown-it-plus@1.0.4
+-- hexo-renderer-stylus@1.1.0
+-- hexo-server@1.0.0
+-- hexo-wordcount@6.0.1
`-- live2d-widget-model-haruto@1.0.5

## Expected behaviour 

我希望点击标签之后跳转到https的链接而不是生成的http链接
![](https://www.image.clzly.xyz/20201028153341.png)

**Comment by liuyib** [comment]
@Keen-King 您好，我没太明白你的意思，能截图示意吗？

**Comment by liuyib** [comment]
@Keen-King 请问您的网站启用 https 了吗？

**Comment by liuyib** [comment]
@Keen-King 请提供你的 Hexo 配置，也就是 Hexo 根目录下 _config.yml 文件的内容

**Comment by Keen-King** [comment]
> @Keen-King 请提供你的 Hexo 配置，也就是 Hexo 根目录下 _config.yml 文件的内容

# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 君匡博客
subtitle: ''
description: 记录君匡的生活工作
keywords: 
author: 君匡
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://www.clzly.xyz/
root: /
permalink: :year/:category/:abbrlink/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex
# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: draft
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: stun


# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: baidu_url_submitter
  - type: git
    repo: keen@39.96.12.167:/home/keen/repos/blog.git
   

baidu_url_submit:
  count: 1000 # 提交最新的一个链接
  host: www.clzly.xyz # 在百度站长平台中注册的域名
  token: vuLb3Rg9Svm2sz55 # 请注意这是您的秘钥， 所以请不要把博客源代码发布在公众仓库里!
  path: baidu_urls.txt # 文本文档的地址， 新链接会保存在此文本文档里

search:
  path: search.json
  field: post
  content: true


live2d:
  enable: true
  scriptFrom: local # 默认
  pluginRootPath: node_modules/ # 插件在站点上的根目录(相对路径)
  pluginJsPath: lib/ # 脚本文件相对与插件根目录路径
  pluginModelPath: assets/ # 模型文件相对与插件根目录路径
  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
  debug: false # 调试, 是否在控制台输出日志
  model:
    use: live2d-widget-model-haruto # npm-module package name
    # use: wanko # 博客根目录/live2d_models/ 下的目录名
    # use: ./wives/wanko # 相对于博客根目录的路径
    # use: https://cdn.jsdelivr.net/npm/live2d-widget-model-wanko@1.0.5/assets/wanko.model.json # 你的自定义 url
  display:
    position: left    
    width: 150
    height: 300
  mobile:
    show: false
  react:
    opacity: 0.7

**Comment by Keen-King** [comment]
> @Keen-King 请问您的网站启用 https 了吗？

抱歉我查阅文档没有发现在哪里启用ssl啊

**Comment by Keen-King** [comment]
我的博客链接是https://www.clzly.xyz/,按照正常来说,点击标签之后应该是跳转的这个页面https://www.clzly.xyz/tags/CCF/
![](https://www.image.clzly.xyz/20201028202103.png)
但是页面下面生成的标签链接是
http://www.clzly.xyz/tags/CCF/
就会自动强制跳转到首页的https://www.clzly.xyz/中

**Comment by liuyib** [comment]
你这里没设置 https 呀：
![image](https://user-images.githubusercontent.com/38221479/97435579-935d0f80-195b-11eb-93e7-b7d9e9208311.png)
你试试把这个改成 https 试试。

**Comment by Keen-King** [comment]
哦哦,我还以为是我自己没有开启哪个属性呢,原来如此我再试试

**Comment by liuyib** [comment]
@Keen-King 可以了么

**Comment by Keen-King** [comment]
> @Keen-King 可以了么？

搞定了,万分感激
