### ISSUE TITLE
”代码高亮“无法识别C#代码

### ISSUE THREAD

**Issue by liangwj45** [liuyib/hexo-theme-stun#12]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:**  v1.3.1

**Platform:**  Windows

**Browser:**  Chrome

## Expected behaviour 

![image](https://user-images.githubusercontent.com/32201368/64698067-c1bc2900-d4d4-11e9-9795-377e1be2b589.png)

## Actual behaviour 

![image](https://user-images.githubusercontent.com/32201368/64698030-ad782c00-d4d4-11e9-9de0-1c0b6e708e83.png)

Other languages display normally.

## Feature Request 

---

**Comment by liuyib** [comment]
你好，这个问题是 Hexo 中默认安装的 Markdown 解析器 `hexo-renderer-marked` 的问题，解析不出 C#
代码。这个解析器功能差强人意，建议将其卸载换成 `hexo-renderer-markdown-it-plus`。

**Comment by liangwj45** [comment]
非常感谢，问题已解决。
