### ISSUE TITLE
可否在 source/_data 目录中使用 i18n 文件

### ISSUE THREAD

**Issue by YadominJinta** [liuyib/hexo-theme-stun#121]
## 我想创建一个新的 issue

- [x] 是的，我已经阅读了 [常见问题](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md)。
- [x] 是的，我已经阅读了 [Stun 的文档](https://theme-stun.github.io/docs/)。

## 预期行为

如题，为了尽量不修改主题文件，可否在hexo根目录下的`languages`或者`source/_data`里使用`i18n`文件，而不是修改主题根目录下的`languages/`中的文件，类似平滑升级中的将主题配置文件放到`source/_data/stun.yml`

## 其他信息

---

**Comment by liuyib** [comment]
@YadominJinta  这个我之前有想过，也有这方面的需求。后面会尝试支持，如果可以实现的话， 3.0 版本之前会进行支持的。感谢建议 ❤️

**Comment by liuyib** [comment]
已实现，见：https://github.com/liuyib/hexo-theme-stun/commit/724d34f353d76a2bce17058f2ad6346a74ef0536

代码暂时还未合并到 master/main 分支，可以克隆 dev 分支上的代码先用着。
