### ISSUE TITLE
用 dist 分支承载主题运行所需的文件（精简文件）

### ISSUE THREAD

**Issue by catch6** [liuyib/hexo-theme-stun#122]
### 目前存在的问题
目前 master 分支包含了太多主题之外的文件，导致了两个问题：
1. 主题文件结构不清晰，不清楚某个文件是干什么的，对于一个非主题开发者而言
2. 增大了主题的体积，比如.eslintrc，doc 等，这些跟主题无关的文件也被使用者拉取到，没必要

除此之外由于git clone 主题后会默认增加.git 文件夹，导致 hexo 根目录在提交的时候需要手动删除主题的.git 文件夹才能正常提交
### 建议
建议 master 分支对.gitignore 修改，增加不必要文件的过滤

**Comment by Flyraty** [comment]
针对第三点可以使用 git submodule 来管理主题

**Comment by liuyib** [comment]
这确实是个好的建议，我之前也思考过这点，但一直也没有落实，既然这里提到，有必要好好考虑下。
我这里有几点解决方法：

- 把文档放入其他仓库，目前已经实施: [Stun new docs](https://github.com/theme-stun/docs)，3.0 版本之后，会把这个仓库中的文档（doc 目录）删除
- 后面会考虑精简 master 分支，或者创建个新分支（如 build）用来存放主题运行所必需的的文件。这样下载主题的时候，指定这个分支，就不会有其他多余的文件了。

如果还有其他比较好的办法，欢迎评论。

**Comment by liuyib** [comment]
该 Issue 提出的需求已经合理地按需采纳，目前的解决方案是：

- 每次将代码 push 到 master 时，通过 CI 将主题运行时需要的文件复制到单独的分支 [dist](https://github.com/liuyib/hexo-theme-stun/tree/dist)，也就是说，dist 分支不会包含任何主题运行无关的文件，极致精简！
- 对于精简 master 分支这个建议不现实，因此这里用 dist 分支承载精简后的文件。
- 对于使用 `git clone` 会在主题目录下生成 `.git` 文件，这个主题没办法控制，即使使用 `git submodule` 指令也与主题无关（需要用户自行控制，毕竟都用指令克隆主题了，肯定也有通过搜索引擎解决这个问题的能力）。
