### ISSUE TITLE
增加控制摘要是否显示的配置

### ISSUE THREAD

**Issue by catch6** [liuyib/hexo-theme-stun#125]
目前要去除所有文章摘要，就需要在每篇文章最前面加入  这种方式太不灵活了，为文章的变动也有负担，能否增加配置项是否启用摘要，关闭的显示效果如下，我是简单且暴力的加了 css 样式
.post-excerpt {
    display: none;
}
但这种方式太 hack 了，最好是在生成阶段就不生成这部分
![Xnip2020-11-10_12-37-55](https://user-images.githubusercontent.com/15259698/98628455-9f7ca000-2351-11eb-9c01-33902f7d05f3.jpg)

**Comment by liuyib** [comment]
@catch6  不知道你是不是想保留部分摘要？或者真的就是不想保留任何摘要，哪怕一个字？

- 如果是想保留部分摘要，见文档：[文章摘要](https://theme-stun.github.io/docs/zh-CN/guide/primary.html#%E6%96%87%E7%AB%A0%E6%91%98%E8%A6%81)
- 如果不想保留任何摘要，你可以指定 Front-Matter 的 `excerpt` 配置：

  ```yaml
  ---
  title: Hello Stun
  excerpt: " " # 注意，值至少包含一个空格
  ---
  ```

  这个 Front-Matter 在 Hexo 4.0 就有了，而且 Stun 主题也很好的支持了，并且也写在了 [Stun 的文档](https://theme-stun.github.io/docs/zh-CN/advanced/advanced.html#front-matter) 里：

  ![image](https://user-images.githubusercontent.com/38221479/98904869-5ebd8c00-24f5-11eb-9a4a-b7323b779fdb.png)

说实话，你这个需求挺奇怪的，如果首页文章不显示摘要，那么它和归档页面，除了样式不同，没啥两样了。

希望能多看看文档。如果觉着文档太多，找不到自己想要的信息，可以利用浏览器的搜索功能 Ctrl + F，然后输入关键字，例如“摘要”，这不就能搜到了：

![snipaste20201112144627](https://user-images.githubusercontent.com/38221479/98905190-f3c08500-24f5-11eb-81e4-5cd71cdefd50.jpg)

**Comment by liuyib** [comment]
这个需求也好实现，加个配置项控制下就好，可以支持。暂时先用上面的方法吧。

**Comment by catch6** [comment]
嗯嗯，文档我倒是从头到尾看了几遍，估计漏掉了，我用你提供的方法吧
