### ISSUE TITLE
高亮颜色方案能更换吗

### ISSUE THREAD

**Issue by catch6** [liuyib/hexo-theme-stun#126]
不是要更换主题，而是当前的上色有点少啊，都分不清类和方法
![Xnip2020-11-12_20-18-13](https://user-images.githubusercontent.com/15259698/98939335-3e58f600-2524-11eb-8c56-e17ff663af37.jpg)

**Comment by liuyib** [comment]
@catch6 莫得办法，Hexo 内置的代码解析器，Stun 主题不考虑自己引入代码高亮解析库。如果想要改善，去给 Hexo 仓库提 Issue 吧。

**Comment by catch6** [comment]
你这个是 hls 吗

**Comment by liuyib** [comment]
highlights ? Hexo 内置的就是 highlights，不过不知道为啥解析效果这么差

**Comment by liuyib** [comment]
不要过分使用缩写，缩写为 hls 的多了去了：
![image](https://user-images.githubusercontent.com/38221479/98939961-33eb2c00-2525-11eb-9bd3-61478daf83ea.png)
增加交流成本

**Comment by catch6** [comment]
好的，晓得了，知道解析效果差的原因了，因为 highlight.js 必须要完整的方法体，我这种中间一段的就不解析了

**Comment by catch6** [comment]
你使用的应该是 Atom One light 的配色方案吧，跟我在 vscode 上的配色挺像的

![image](https://user-images.githubusercontent.com/15259698/98940676-4e71d500-2526-11eb-9943-6206cc5f18b2.png)

**Comment by liuyib** [comment]
> 你使用的应该是 Atom One light 的配色方案吧，跟我在 vscode 上的配色挺像的
> 
> ![image](https://user-images.githubusercontent.com/15259698/98940676-4e71d500-2526-11eb-9943-6206cc5f18b2.png)

配色方案是参考现有的自己调的
