### ISSUE TITLE
怎么实现自定义页面不显示sidebar

### ISSUE THREAD

**Issue by benjamin603** [liuyib/hexo-theme-stun#127]
## Your feedback

🚀 怎么实现自定义页面禁用sidebar，不影响其他页面！

**Comment by liuyib** [comment]
在你想要禁用 sidebar 的页面对应的 Markdown 文件中，Font-Matter 里设置：

```yml
sidebar: false
```

**Comment by liuyib** [comment]
在你想要禁用 sidebar 的页面对应的 Markdown 文件中，Front-Matter 里设置：

```yml
sidebar: false
```

**Comment by liuyib** [comment]
这个功能之前就支持了，忘了写到文档里了，已更新文档：[sidebar - 是否显示侧边栏](https://theme-stun.github.io/docs/zh-CN/advanced/advanced.html#sidebar-%E6%98%AF%E5%90%A6%E6%98%BE%E7%A4%BA%E4%BE%A7%E8%BE%B9%E6%A0%8F)

**Comment by benjamin603** [comment]
> 这个功能之前就支持了，忘了写到文档里了，已更新文档：[sidebar - 是否显示侧边栏](https://theme-stun.github.io/docs/zh-CN/advanced/advanced.html#sidebar-%E6%98%AF%E5%90%A6%E6%98%BE%E7%A4%BA%E4%BE%A7%E8%BE%B9%E6%A0%8F)

谢谢，搞定！
