### ISSUE TITLE
主题 v1.4.0 存在错误无法运行，请更新主题到最新版

### ISSUE THREAD

**Issue by MintGreenTZ** [liuyib/hexo-theme-stun#13]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version: 1.4.0** 

**Platform: Windows** 

**Browser: Chrome** 

## Expected behaviour 
show local blog after I enter "hexo clean && hexo s" and open "http://localhost:4000/"

## Actual behaviour 

When I enter "hexo clean && hexo s", it's still okey.
<img width="631" alt="before" src="https://user-images.githubusercontent.com/44612257/64698918-570bed00-d4d6-11e9-958c-6c1b20e7db16.png">
But when I try to open "http://localhost:4000/", bug appears.
<img width="962" alt="typeError" src="https://user-images.githubusercontent.com/44612257/64699081-a3572d00-d4d6-11e9-8b5c-7bfc5766992a.png">

## Steps to reproduce the behaviour 
hexo clean && hexo s
open "http://localhost:4000/"

## Feature Request 

---

**Comment by liuyib** [comment]
你好，这个错误的原因是因为，我在版本发布之前错误的打开了默认不应该打开的配置项。很抱歉，这是我的一个疏漏。我会立即发布新的版本来修复这个错误。 @MintGreenTZ

**Comment by liuyib** [comment]
最新版已发布：[v1.4.1](https://github.com/liuyib/hexo-theme-stun/releases/tag/v1.4.1)，更新到这个版本即可解决问题。抱歉我的疏忽给你造成了麻烦 🙏。以后我会更加认真对待版本发布，如果可以的话，给个 star 🤗。
