### ISSUE TITLE
装了个hexo-asset-image然后出现了乱码

### ISSUE THREAD

**Issue by ShanZJ-gvs** [liuyib/hexo-theme-stun#130]
出现了乱码....内容没有乱码
大佬求解​:cry:​
![image](https://user-images.githubusercontent.com/59501014/100299542-eb287e00-2fce-11eb-982f-a426f303c69b.png)
![image](https://user-images.githubusercontent.com/59501014/100299611-0dba9700-2fcf-11eb-84e2-afe1ea1f7d0b.png)
![image](https://user-images.githubusercontent.com/59501014/100299637-1d39e000-2fcf-11eb-8ed8-2e85df0907f9.png)

**Comment by ShanZJ-gvs** [comment]
博客地址http://www.gvssimux.com/

**Comment by liuyib** [comment]
@ShanZJ-gvs 解决了吗？

我看网上有相应的文章：https://cosysn.github.io/2017/07/17/hexo-chinese-unintelligible-text/

**Comment by ShanZJ-gvs** [comment]
> @ShanZJ-gvs 解决了吗？
> 
> 我看网上有相应的文章：https://cosysn.github.io/2017/07/17/hexo-chinese-unintelligible-text/

我把插件删除后，重启了下服务器，现在好了，感谢~~~
