### ISSUE TITLE
文章详情页面的顶部大图和标题区别开

### ISSUE THREAD

**Issue by niumoo** [liuyib/hexo-theme-stun#132]
## 文章详情页面的顶部大图和标题

- [x] 是的，我已经阅读了 [常见问题](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md)。
- [x] 是的，我已经阅读了 [Stun 的文档](https://theme-stun.github.io/docs/)。

## 理想状态

首页的顶部大图和信，应该和文章详情页面的顶部大图内容有所不同。
首页：自定义大图，文字描述为网站标题等信息
文章页面：自定义大图，图上描述为当前文章标题和相关信息。

感觉这样才有意义，不然文章详情页开启了只是换个背景，描述还是网站信息总觉得有点古怪。

## 实际行为
首页的顶部大图和信，应该和文章详情页面的顶部大图内容完全一样

**Comment by liuyib** [comment]
@niumoo 您好，主题当时就是这样设计的，不会修改的。
