### ISSUE TITLE
使用的时候TOC目录不能突然不能点击跳转了

### ISSUE THREAD

**Issue by z-jeff953** [liuyib/hexo-theme-stun#138]
使用的时候TOC目录不能突然不能点击跳转了

**Comment by liuyib** [comment]
所有的toc都是吗？还是某篇文章的？请提供截图，代码示例等一切能帮助我定位问题的信息。你提供的信息越充足，我这边定位问题越方便。还有为啥你不按照issue模板提问，环境信息，stun版本信息都提供下


 
---原始邮件---
发件人: "jeffords"<notifications@github.com&gt;
发送时间: 2020年12月14日 11:48:23
收件人: "liuyib/hexo-theme-stun"<hexo-theme-stun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [liuyib/hexo-theme-stun] 使用的时候TOC目录不能突然不能点击跳转了 (#138)




 
使用的时候TOC目录不能突然不能点击跳转了

**Comment by liuyib** [comment]
如果你不用心提供尽可能多的信息，以至于我定位不到问题，那么这个issue将被关闭


 
---原始邮件---
发件人: "jeffords"<notifications@github.com&gt;
发送时间: 2020年12月14日 11:48:23
收件人: "liuyib/hexo-theme-stun"<hexo-theme-stun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [liuyib/hexo-theme-stun] 使用的时候TOC目录不能突然不能点击跳转了 (#138)




 
使用的时候TOC目录不能突然不能点击跳转了

**Comment by z-jeff953** [comment]
感谢你的回复，我后来发现是使用narkdown-it-plus产生的问题，卸载了之后换一个就行了hh------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;EvanOne（文一）&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年12月14日(星期一) 中午11:52
收件人:&nbsp;&quot;liuyib/hexo-theme-stun&quot;<hexo-theme-stun@noreply.github.com&gt;;
抄送:&nbsp;&quot;jeffords&quot;<1572754810@qq.com&gt;;&quot;Author&quot;<author@noreply.github.com&gt;;
主题:&nbsp;Re: [liuyib/hexo-theme-stun] 使用的时候TOC目录不能突然不能点击跳转了 (#138)

**Comment by liuyib** [comment]
👌🏻👌🏻👌🏻，麻烦吧 issue 关了吧


 
---原始邮件---
发件人: "jeffords"<notifications@github.com&gt;
发送时间: 2020年12月14日 12:03:44
收件人: "liuyib/hexo-theme-stun"<hexo-theme-stun@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"EvanOne（文一）"<1656081615@qq.com&gt;;
主题: Re: [liuyib/hexo-theme-stun] 使用的时候TOC目录不能突然不能点击跳转了 (#138)




 感谢你的回复，我后来发现是使用narkdown-it-plus产生的问题，卸载了之后换一个就行了hh------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;&amp;quot;EvanOne（文一）&amp;quot;<notifications@github.com&amp;gt; 
 发送时间:&amp;nbsp;2020年12月14日(星期一) 中午11:52 
 收件人:&amp;nbsp;&amp;quot;liuyib/hexo-theme-stun&amp;quot;<hexo-theme-stun@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;&amp;quot;jeffords&amp;quot;<1572754810@qq.com&amp;gt;;&amp;quot;Author&amp;quot;<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [liuyib/hexo-theme-stun] 使用的时候TOC目录不能突然不能点击跳转了 (#138)
