### ISSUE TITLE
新版本在 source/_data 目录中缺乏 i18n 文件出错

### ISSUE THREAD

**Issue by yeung66** [liuyib/hexo-theme-stun#149]
## 我想创建一个新的 issue

- [x] 是的，我已经阅读了 [常见问题](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md)。
- [x] 是的，我搜索并阅读了 [Issues 列表](https://github.com/liuyib/hexo-theme-stun/issues)（包括关闭的），但是没有帮助到我。
- [x] 是的，我是第一次使用 Stun 主题。
- [x] 是的，我之前用过 Stun 主题，并且可以正常运行。但是当我做了一些更改后，主题就无法正常运行了。
- [x] 是的，我使用了 [平滑升级](https://theme-stun.github.io/docs/zh-CN/advanced/advanced.html#%E5%B9%B3%E6%BB%91%E5%8D%87%E7%BA%A7) 的特性，并且阅读了其文档。

## 环境信息

**Stun 版本：**

2.6.0

**Hexo 版本：**

 5.2.0

---

在新版本添加关于在 `source/_data` 目录下使用 i18n 文件的新 [feature](https://github.com/liuyib/hexo-theme-stun/issues/121) 之后，如果 source/_data 目录下没有 languages 文件夹，会导致 hexo 运行时出错，如命令 `hexo s` ，即使主题文件夹下面有 languages 文件夹。

感觉这个应该加个判断，如果 source/_data 目录下面没有语言文件，则使用主题里面的 i18n 文件，不然就会直接运行出错。

**Comment by liuyib** [comment]
@yeung66 感谢你的反馈，这个确实是我的疏忽，很抱歉对您造成的麻烦。该问题已在 [v2.6.1](https://github.com/liuyib/hexo-theme-stun/releases/tag/v2.6.1) 版本中进行修复。
