### ISSUE TITLE
生成太多 archives 页面

### ISSUE THREAD

**Issue by yeung66** [liuyib/hexo-theme-stun#150]
## 我想创建一个新的 issue

- [x] 是的，我已经阅读了 [常见问题](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md)。
- [x] 是的，我搜索并阅读了 [Issues 列表](https://github.com/liuyib/hexo-theme-stun/issues)（包括关闭的），但是没有帮助到我。
- [x] 是的，我是第一次使用 Stun 主题。
- [x] 是的，我之前用过 Stun 主题，并且可以正常运行。但是当我做了一些更改后，主题就无法正常运行了。
- [x] 是的，我使用了 [平滑升级](https://theme-stun.github.io/docs/zh-CN/advanced/advanced.html#%E5%B9%B3%E6%BB%91%E5%8D%87%E7%BA%A7) 的特性，并且阅读了其文档。

## 环境信息

**Stun 版本：**

2.6.0

**Hexo 版本：**

5.2.0

---

更新到 2.6.0 版本后，生成的 archives 页面数量太多了，似乎是给每个年份，每个月份都生成了一个 archives 页面，而且内容还是一样的，效果大概如下

- [https://scottyeung.top/archives/2018/10/](https://scottyeung.top/archives/2018/10/)
- [https://scottyeung.top/archives/2018/](https://scottyeung.top/archives/2018/)
- [https://scottyeung.top/archives/](https://scottyeung.top/archives/)

这三个是内容相同的不同页面，在 public 文件夹也可以看到

（在作者的博客好像也能看到这个现象

**Comment by liuyib** [comment]
@yeung66 你好，这个其实不是 Bug，这是 [hexo-generator-archive](https://github.com/hexojs/hexo-generator-archive) 插件默认的配置：

```yml
archive_generator:
  enabled: true
  per_page: 10
  yearly: true
  monthly: true
  daily: false
  order_by: -date
```

把其中的 `yearly`、`monthly` 都设置成 `false` 就好了：

```diff
 archive_generator:
   enabled: true
   per_page: 10
+  yearly: false
+  monthly: false
   daily: false
   order_by: -date
```

**Comment by yeung66** [comment]
然而这个也没有按照年月日归档的效果，生成的归档页面都是一样的

（之前都没有这样的现象，`archive_generator` 这个之前也没有配置过，好像是主题升级到 2.6.0 版本后才出现的

**Comment by yeung66** [comment]
在 hexo 的配置文件下面添加配置好了，不会再为每年每月生成归档页面

不过感觉这个的配置其实最好能在主题配置文件下也放一个，因为大多数人（例如我）都是没有配置直接使用默认值的。

**Comment by liuyib** [comment]
> 在 hexo 的配置文件下面添加配置好了，不会再为每年每月生成归档页面
> 
> 不过感觉这个的配置其实最好能在主题配置文件下也放一个，因为大多数人（例如我）都是没有配置直接使用默认值的。

1. 我也发现并没有按年月日归档的效果，生成的归档页都一样，这是插件的问题。
2. 这个是 Hexo 的插件，配置当然要放在 Hexo 的 _config.yml 中，没必要放在主题的配置文件中（如果有些配置需要放在主题的配置文件中，我肯定会放的）。
3. 我也是直接使用插件的默认配置，这是因为我们都信任插件的默认配置最合理。但你的需求已经违背了插件的默认功能，当然要自己改配置了。

最后，感谢对 Stun 主题的支持 :heart:
