### ISSUE TITLE
能不能加个输入密码查看的功能~

### ISSUE THREAD

**Issue by sjsmi1e** [liuyib/hexo-theme-stun#155]
## 我想创建一个新的 issue

- [] 是的，我已经阅读了 [常见问题](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md)。
- [] 是的，我已经阅读了 [Stun 的文档](https://theme-stun.github.io/docs/)。

## 其他信息

---

**Comment by liuyib** [comment]
这个功能已经有插件实现了：https://github.com/D0n9X1n/hexo-blog-encrypt/blob/master/ReadMe.zh.md，直接用插件就可以了 🙌
