### ISSUE TITLE
文章标题上的行内公式无法正常渲染

### ISSUE THREAD

**Issue by PHIKN1GHT** [liuyib/hexo-theme-stun#156]
## 我想创建一个新的 issue

- [x] 是的，我已经阅读了 [常见问题](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md)。
- [x] 是的，我搜索并阅读了 [Issues 列表](https://github.com/liuyib/hexo-theme-stun/issues)（包括关闭的），但是没有帮助到

## 预期行为
页面中包括文章标题在内的行内公式应该全部能够得到渲染

## 实际行为
在开启了mathjax且允许行内公式的情况下，正文内（包括正文内的各级标题）的公式皆可以正常渲染，但文章题目/标题的行内公式会被忽略

## 重现步骤
正确进行配置后，在标题内加入行内公式便可以轻易复现

**Comment by liuyib** [comment]
@PHIKN1GHT 您好，该问题确实存在，很快会修复，感谢反馈 :heart:

**Comment by liuyib** [comment]
@PHIKN1GHT  问题已解决，见：[v2.6.2](https://github.com/liuyib/hexo-theme-stun/releases/tag/v2.6.2)，再次感谢反馈 :heart:

**Comment by PHIKN1GHT** [comment]
感谢修复。我试了一下，主页和文章内的显示确实都能正常生效了。但是在archives页面里好像依然没有生效？也包括在tags/categories页面内具体选择某个选项后显示的文章列表。

**Comment by liuyib** [comment]
数学公式只能渲染在 markdown 文件对应的地方，简单来说，文章/页面这些都是能找到对应的 md 文件的，这样的地方可以渲染数学公式。而 archives 和 tags/categories页面内具体选择某个选项后显示的文章列表，这些都是自动生成的，暂时是无法渲染数学公式的。

我看了现有的一些数学公式渲染方案：

- 使用插件 [hexo-math](https://github.com/hexojs/hexo-math)
- 【安装能解析数学公式的插件 hexo-renderer-markdown-it-plus 等】 + 【Stun 提供的 math 配置项】/【使用 hexo-filter-mathjax】

这些都没法在你提到的 archives 等页面中渲染数学公式。另外我想了一下，一般不会把数学公式放在文章的大标题中吧 😂
