### ISSUE TITLE
stun文档网站访问不了了 能不能部署在码云 或者把代码源码建立一个仓库 我们可以自己运行查看 主题用一年了，今天突然要改一点配置没有文档看着头大

### ISSUE THREAD

**Issue by desire599** [liuyib/hexo-theme-stun#158]
## stun文档网站访问不了了 能不能部署在码云 或者把代码源码建立一个仓库 我们可以自己运行查看 主题用一年了，今天突然要改一点配置没有文档看着头大

**Comment by lzkids** [comment]
你看看是不是你的网有问题？我这边就能正常访问

**Comment by lzkids** [comment]
> ## stun文档网站访问不了了 能不能部署在码云 或者把代码源码建立一个仓库 我们可以自己运行查看 主题用一年了，今天突然要改一点配置没有文档看着头大
你看看是不是你的网有问题？我这边就能正常访问

**Comment by lzkids** [comment]
> ## stun文档网站访问不了了 能不能部署在码云 或者把代码源码建立一个仓库 我们可以自己运行查看 主题用一年了，今天突然要改一点配置没有文档看着头大

https://theme-stun.github.io/docs/zh-CN/

**Comment by desire599** [comment]
访问不了哎 我一个多月前发现我之前部署在GitHub上的博客也访问不了 是不是GitHub pages






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "lz"<notifications@github.com&gt;; 
发送时间: 2021年1月25日(星期一) 晚上10:45
收件人: "liuyib/hexo-theme-stun"<hexo-theme-stun@noreply.github.com&gt;; 
抄送: "1197780293"<1197780293@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [liuyib/hexo-theme-stun] stun文档网站访问不了了 能不能部署在码云 或者把代码源码建立一个仓库 我们可以自己运行查看 主题用一年了，今天突然要改一点配置没有文档看着头大 (#158)





 
你看看是不是你的网有问题？我这边就能正常访问

**Comment by desire599** [comment]
果然 我在外地的同学可以访问 在本地的同学都不行

**Comment by desire599** [comment]
刚用vpn可以访问了 我之前部署的博客也可以访问了 我开始还以为是GitHub pages不能使用了呢

**Comment by lzkids** [comment]
> 刚用vpn可以访问了 我之前部署的博客也可以访问了 我开始还以为是GitHub pages不能使用了呢

也有可能是网络的问题，感觉不可能限制。对了问一下你点击文章的时候，网站顶部会自动收起吗？

**Comment by desire599** [comment]
不会自动收起  顶部是全部展开的，哎 我开始还以为是github page用不了了 直到今天才知道是网络原因 百度也有类似跟我一样的问题 我几个外地同学都可以访问  本地的同学都不行 不知道是不是域名被污染了还是什么问题 1197780293 邮箱：1197780293@qq.com 签名由 网易邮箱大师 定制 在2021年01月25日 23:49，lz 写道： 刚用vpn可以访问了 我之前部署的博客也可以访问了 我开始还以为是GitHub pages不能使用了呢 也有可能是网络的问题，感觉不可能限制。对了问一下你点击文章的时候，网站顶部会自动收起吗？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by liuyib** [comment]
> > 刚用vpn可以访问了 我之前部署的博客也可以访问了 我开始还以为是GitHub pages不能使用了呢
> 
> 也有可能是网络的问题，感觉不可能限制。对了问一下你点击文章的时候，网站顶部会自动收起吗？

“点击文章的时候，网站顶部会自动收起”这需要开启 Pjax，然后设置 `pjax.avoidBanner` 为 `true` 就可以了

**Comment by liuyib** [comment]
我去弄下 gitee page，只有 github page 确实不太好

**Comment by liuyib** [comment]
已在码云托管 stun 的文档：https://theme-stun.gitee.io/docs/

**Comment by liuyib** [comment]
文档里的图片还是使用的 github 的服务，后面会进一步考虑将图片一块迁移
