### ISSUE TITLE
小白求问，首页的文章如何设置为收起的，我的都在展开着，请问怎么设置？

### ISSUE THREAD

**Issue by Keafmd** [liuyib/hexo-theme-stun#159]
## 你的反馈

我想也设置个阅读全文然后在展开的效果，感谢回复！
---

**Comment by four-two** [comment]
https://theme-stun.github.io/docs/zh-CN/guide/primary.html#%E8%BF%94%E5%9B%9E%E9%A1%B6%E9%83%A8

**Comment by Keafmd** [comment]
> https://theme-stun.github.io/docs/zh-CN/guide/primary.html#%E8%BF%94%E5%9B%9E%E9%A1%B6%E9%83%A8

非常感谢，可以了，感谢！

**Comment by liuyib** [comment]
可以看看文档中，文章摘要部分：https://theme-stun.github.io/docs/zh-CN/guide/primary.html#%E6%96%87%E7%AB%A0%E6%91%98%E8%A6%81
