### ISSUE TITLE
本文链接中文乱码

### ISSUE THREAD

**Issue by GarfieldCCC** [liuyib/hexo-theme-stun#170]
![image](https://user-images.githubusercontent.com/31843721/110872814-7d992700-830b-11eb-84a3-85d8a3525680.png)
在本文链接这里，如果我的文章标题有中文，就会乱码，请问这个要怎么解决呢

**Comment by liuyib** [comment]
这不是乱码，这是 URL 编码，如果不想这样，自己把 markdown 文件用英文命名
 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年3月12日 08:19:17
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [liuyib/hexo-theme-stun] 本文链接中文乱码 (#170)




 

 在本文链接这里，如果我的文章标题有中文，就会乱码，请问这个要怎么解决呢

**Comment by GarfieldCCC** [comment]
没有办法让他正常显示中文吗

**Comment by lzkids** [comment]
@GarfieldCCC 暂时没办法好像是，还有一种办法是可以使用插件，让插件为每一篇文章分配abbrlink属性，这样会使文章的url变得非常简洁，例如 https://xxx.xx/xxxx/3055NXV.html 类似于这样

**Comment by GarfieldCCC** [comment]
> @GarfieldCCC 暂时没办法好像是，还有一种办法是可以使用插件，让插件为每一篇文章分配abbrlink属性，这样会使文章的url变得非常简洁，例如 3055NXV.html 类似于这样——数字加字母

太感谢了，你拯救了一个强迫症患者

**Comment by lzkids** [comment]
> 
> 
> > @GarfieldCCC 暂时没办法好像是，还有一种办法是可以使用插件，让插件为每一篇文章分配abbrlink属性，这样会使文章的url变得非常简洁，例如 3055NXV.html 类似于这样——数字加字母
> 
> 太感谢了，你拯救了一个强迫症患者
推荐使用这个hexo-enhancer这是一个增强插件（类似插件包）也可以去hexo插件库找
