### ISSUE TITLE
能不能加个实时发布说说的功能？

### ISSUE THREAD

**Issue by lzkids** [liuyib/hexo-theme-stun#174]
## 我想创建一个新的 issue

- [x] 是的，我已经阅读了 [常见问题](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md)。
- [x] 是的，我已经阅读了 [Stun 的文档](https://theme-stun.github.io/docs/)。

## 其他信息
https://artitalk.js.org/
这是网址😁是基于LeanCloud实现的
有没有考虑集成下？
---

**Comment by liuyib** [comment]
抱歉，暂时不考虑集成。
