### ISSUE TITLE
文章里插入xml代码段时，代码显示不完整

### ISSUE THREAD

**Issue by coortop** [liuyib/hexo-theme-stun#19]
![QQ截图20191017150644](https://user-images.githubusercontent.com/49756728/66985636-cd13fd00-f0ef-11e9-853f-f06b40e98c1a.png)

![QQ截图20191017150917](https://user-images.githubusercontent.com/49756728/66985833-385dcf00-f0f0-11e9-964f-afe3746afb62.png)

半个括号不见了，不知道是主题问题还是hexo的问题，就是不显示</

**Comment by coortop** [comment]
可以邮箱回复
2058930674@qq.com

**Comment by liuyib** [comment]
这个问题我之前也遇到了，你是不是使用了 [hexo-all-minifier](https://github.com/chenzhutian/hexo-all-minifier) 这个插件？

**Comment by coortop** [comment]
我找了下好像并没有装这个插件

**Comment by coortop** [comment]
也就是说是某个插件冲突造成的是吧

**Comment by liuyib** [comment]
还不太确定，我之前和你一样的问题是  hexo-all-minifier 这个插件造成的。麻烦你把 hexo 根目录下的 package.json 文件 和 _config.yml 文件内容贴出来我看下。

**Comment by coortop** [comment]
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate"
  },
  "hexo": {
    "version": "3.9.0"
  },
  "dependencies": {
    "cheerio": "^1.0.0-rc.3",
    "hexo": "^3.9.0",
    "hexo-browsersync": "^0.3.0",
    "hexo-deployer-git": "^2.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^2.0.0",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-render-pug": "^2.1.4",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-jade": "^0.4.1",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3",
    "hexo-wordcount": "^6.0.1",
    "install": "^0.13.0",
    "request": "^2.88.0",
    "xml-parser": "^1.2.1",
    "yamljs": "^0.3.0"
  }
}





# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 弥枳'blog
subtitle:
description:
keywords: 弥枳,弥枳'blog
author: 弥枳
language: zh-CN
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://blog.coor.top
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: coor

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repository: 
      github: https://github.com/coortop/coortop.github.io.git
      coding: https://e.coding.net/coortop/coortop.coding.me.git
  branch: master

**Comment by coortop** [comment]
这格式怎么关

**Comment by liuyib** [comment]
我替你改正格式了，你点编辑看下怎么改的。你安装的一些插件我没用过，我感觉和 `xml-parser` 这个解析有关。另外 hexo 里面不需要安装第三方插件来解析 xml 语法，直接写 markdown 这样：
![image](https://user-images.githubusercontent.com/38221479/66988106-8a085880-f0f4-11e9-88e7-e8ae8f561905.png)
就能解析。

**Comment by coortop** [comment]
```xml
<!--spring-->
  <context-param>
    <param-name>contextConfigLocation</param-name>
    <param-value>classpath:spring/applicationContext*.xml</param-value>
  </context-param>
```


你试试这段

**Comment by liuyib** [comment]
![image](https://user-images.githubusercontent.com/38221479/66988393-07cc6400-f0f5-11e9-8907-97e0c4816c31.png)

我这边没问题。

**Comment by coortop** [comment]
![QQ截图20191017154350](https://user-images.githubusercontent.com/49756728/66988342-f6835780-f0f4-11e9-84a3-51da2f88d976.png)
![QQ截图20191017154445](https://user-images.githubusercontent.com/49756728/66988427-1286f900-f0f5-11e9-812f-76a93673af7e.png)

**Comment by liuyib** [comment]
你这个问题是markdown 解析的问题，和主题无关，应该是某个插件造成的，你行卸载一些插件试试吧。我安装的插件是这些，你参考下：

![image](https://user-images.githubusercontent.com/38221479/66988755-a062e400-f0f5-11e9-9891-c9a873f2bb3c.png)

**Comment by liuyib** [comment]
麻烦你在问题解决后，在这里贴一下原因，这样其他人遇到同样问题，可以做参考 😊。

**Comment by coortop** [comment]
好的，我先找问题

**Comment by coortop** [comment]
卸载插件命令咋写，刚接触，用的Git bash here
哈哈，我先去做饭

**Comment by coortop** [comment]
我换了好多插件，现在基本换的和你一样了
但是我刚注意点一个新问题，就是不显示注释，也就是说有东西把注释帮忙隐藏了
那半个括号应该也是当做注释隐藏了的

![QQ截图20191017173947](https://user-images.githubusercontent.com/49756728/66997535-3baf8580-f105-11e9-98a2-19dfefab0ea1.png)

![QQ截图20191017174005](https://user-images.githubusercontent.com/49756728/66997536-3baf8580-f105-11e9-956d-6259fb694de9.png)

![QQ截图20191017174017](https://user-images.githubusercontent.com/49756728/66997537-3c481c00-f105-11e9-9711-8c4b015e76ea.png)
可能就是哪里的配置文件设置了

**Comment by coortop** [comment]
你看看我刚回复的，找到原因了，不知道咋解决

**Comment by coortop** [comment]
我重装了一下hexo问题解决了，之前hexo版本3.9.0，现在hexo版本4.0.0

**Comment by liuyib** [comment]
看来确实是 hexo 的问题，👍
