### ISSUE TITLE
hexo d 部署失败

### ISSUE THREAD

**Issue by hiBenzhu** [liuyib/hexo-theme-stun#197]
github官方给我发来一封邮件

> The page build failed for the `master` branch with the following error:
> 
> Unable to build page. Please try again later.
> 
> For information on troubleshooting Jekyll see:
> 
>   https://docs.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can submit a request at https://support.github.com/contact?repo_id=353965241&page_build_id=253555797

**小白不知道如何解决，请问有没有大神可以救一下**

**Comment by Flyraty** [comment]
> github官方给我发来一封邮件
> 
> > The page build failed for the `master` branch with the following error:
> > Unable to build page. Please try again later.
> > For information on troubleshooting Jekyll see:
> > https://docs.github.com/articles/troubleshooting-jekyll-builds
> > If you have any questions you can submit a request at https://support.github.com/contact?repo_id=353965241&page_build_id=253555797
> 
> **小白不知道如何解决，请问有没有大神可以救一下**
遇到了同样的问题，首先检查下 markdowm 文档名称及内容是否存在部分非法字符导致 pages 构建失败吧。

**Comment by Flyraty** [comment]
> > github官方给我发来一封邮件
> > > The page build failed for the `master` branch with the following error:
> > > Unable to build page. Please try again later.
> > > For information on troubleshooting Jekyll see:
> > > https://docs.github.com/articles/troubleshooting-jekyll-builds
> > > If you have any questions you can submit a request at https://support.github.com/contact?repo_id=353965241&page_build_id=253555797
> > 
> > 
> > **小白不知道如何解决，请问有没有大神可以救一下**
> > 遇到了同样的问题，首先检查下是否为 markdowm 文档名称及内容存在非法字符导致 pages 构建失败吧。

**Comment by JerrySheh** [comment]
same here. 应该是 github 的问题，看他们的公告（https://www.githubstatus.com/），现在应该修复了，可以再尝试一下。

**Comment by Flyraty** [comment]
> same here. 应该是 github 的问题，看他们的公告（ https://www.githubstatus.com/ ），现在应该修复了，可以再尝试一下。

thanks

**Comment by hiBenzhu** [comment]
> 同样在这里。应该是github的问题，看他们的公告（https://www.githubstatus.com/），现在应该修复了，可以再尝试一下。

感谢，现在已经好了
