### ISSUE TITLE
标题修改

### ISSUE THREAD

**Issue by hiBenzhu** [liuyib/hexo-theme-stun#199]
请教如何修改**移动端**header的标题文字大小
![1](https://user-images.githubusercontent.com/81456172/118639584-a86f9200-b80a-11eb-8712-c44f38cfe92e.png)

**Comment by YiHui-Liu** [comment]
直接修改styl文件，可以在`source/css/_custom/_common.styl`中修改

**Comment by liuyib** [comment]
文档里有说明，看下[自定义样式修改](https://theme-stun.github.io/docs/zh-CN/advanced/advanced.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E6%A0%B7%E5%BC%8F)就知道了。 @hiBenzhu
