### ISSUE TITLE
按照文档配置后，更换不了主题。网页显示如下

### ISSUE THREAD

**Issue by pauperbahar** [liuyib/hexo-theme-stun#2]
n/layout.pug block content include ./_mixins/posts-sort.pug include ./_mixins/post-header.pug div.home-content.code-highlight if theme.post_list_paged.home include ./_components/recent-posts.pug include ./_components/pagination.pug else include ./_components/recent-posts.pug

**Comment by liuyib** [comment]
这个是因为没有安装对 pug 的支持。文档里**安装**那部分说了，如果没有安装对 pug、stylus 的支持执行指令：`npm install --save-dev hexo-render-pug hexo-renderer-stylus`，不确定的话直接执行就好了。
还有问题的话可以重新打开这个 issue。

**Comment by Greatpride** [comment]
extends ./_layout.pug block content include ./_partials/post/post-list.pug if theme.post_list.paginate.home include ./_partials/widgets/paginator.pug

**Comment by Greatpride** [comment]
更换主题后出现的问题

**Comment by Greatpride** [comment]
> 
> 
> 更换主题后出现的问题

安装了`npm install hexo-renderer-pug --save`
还有问题
