### ISSUE TITLE
The icon of paginator can't display normally

### ISSUE THREAD

**Issue by ds934118** [liuyib/hexo-theme-stun#20]
## I want to create a new issue 

- [X] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [X] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [X] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [X] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** 
Newest(1.5.3?)

**Platform:** Windows/macOS/Android

**Browser:**  CHrome/FireFox

## Actual behaviour 

![2019-10-25_145240](https://user-images.githubusercontent.com/5456589/67550130-52bf2a80-f738-11e9-9898-58c085b737cd.jpg)

## Steps to reproduce the behaviour 

- I don't know how to reproduce the problem, but it seems that the section in the .pug file is not compiled correctly by template engine. 

![2019-10-25_145337](https://user-images.githubusercontent.com/5456589/67550131-5357c100-f738-11e9-8963-bcfefec630c2.jpg)

![2019-10-25_150817](https://user-images.githubusercontent.com/5456589/67550489-3079dc80-f739-11e9-8701-94e1fbc7896a.jpg)

## Feature Request 

---

**Comment by liuyib** [comment]
What is your Hexo version?

**Comment by liuyib** [comment]
I found the reason in the breaking change of the hexo 4.0 version, and reproduced it:

![snipaste20191026101015](https://user-images.githubusercontent.com/38221479/67612877-a03fa400-f7d9-11e9-966f-57e8af80e461.jpg)

So, I will support the breaking change of hexo as soon as possible, then your problem will solved.

**Comment by liuyib** [comment]
@ds934118  Solved: [fix(#20): Solved that the paginator can't show normally](https://github.com/liuyib/hexo-theme-stun/commit/7d321bc87d6997a0749fffd02703df75b9299ac4).

**Comment by ds934118** [comment]
Thanks for your helping.
