### ISSUE TITLE
文章标题如果换行，下划线长度与位置不对

### ISSUE THREAD

**Issue by cbsfly** [liuyib/hexo-theme-stun#206]
## 实际行为

主页标题过长后

![image](https://user-images.githubusercontent.com/16754284/120993381-0cf09200-c7b6-11eb-92cc-2a12c257b9bd.png)

![image](https://user-images.githubusercontent.com/16754284/121000251-930fd700-c7bc-11eb-95ab-958242e88882.png)

**Comment by liuyib** [comment]
@cbsfly 这个不是 bug，这个下划线是 css 实现的，默认就是到第二行的最后一个字，看着确实有点怪异哈，但暂时先这样。感谢反馈 :hearts:
