### ISSUE TITLE
加粗样式不能显示

### ISSUE THREAD

**Issue by Arost01** [liuyib/hexo-theme-stun#209]
![image](https://user-images.githubusercontent.com/56621038/122694638-9bfab100-d270-11eb-8fb2-1d784420f14d.png)

**Comment by liuyib** [comment]
@Arost01 这是你的 Markdown 语法书写错误哦！

这里加个空格才是对的：

![image](https://user-images.githubusercontent.com/38221479/126024278-19d74748-20ca-4f28-ad3c-103595e1ad82.png)
