### ISSUE TITLE
首屏下拉提示箭头

### ISSUE THREAD

**Issue by oriberisa** [liuyib/hexo-theme-stun#21]
感觉作者提供这么好的主题，用了几天体验很不错，提这个不是核心需求，只是觉得有个首页背景图全屏情况下有个下滑提示自然一点。类似于这个Fluid主题这个，https://0x2e.github.io/

**Comment by liuyib** [comment]
这个可以有

**Comment by liuyib** [comment]
已实现：[https://github.com/liuyib/hexo-theme-stun/commit/c05223ad85aa386941e246701824148fc93527e7](https://github.com/liuyib/hexo-theme-stun/commit/c05223ad85aa386941e246701824148fc93527e7)。更新主题版本后，修改配置文件里的配置项 `scroll_down_icon` 即可启用。
