### ISSUE TITLE
给侧边栏的作者信息添加"name"和"location"版块

### ISSUE THREAD

**Issue by wxdrizzle** [liuyib/hexo-theme-stun#214]
## I want to create a new issue

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read the documents of [Stun](https://theme-stun.github.io/docs/).

## Expected behaviour
侧边栏的作者信息中，希望能包含姓名和位置两个额外信息。从而从上到下形成 avatar-name-motto-location的格局。样式上，name可以与现有的motto一致，而motto可以字体比name细一点（甚至泛化为description, 即一句话自我介绍），location在字体细一点的同时，前面加一个图钉标志（例如fa-map-marker-alt，甚至让用户定制图标）。 

## Actual behaviour
目前侧边栏的作者信息只有avatar和motto

## Other Information
您觉得这项新功能有添加的必要吗？如果您比较忙，我可以参与这项feature的开发，并提交pul request。只是我不熟悉nodejs, hexo相关语法。目前已经fork stun主题，正在 layout/_partials/sidebar.sidebar.pug 和 source/css/_common/components/sidebar/index.styl 这两个文件中，参考已有代码的语法进行尝试。

最后，感谢您开发了stun这个简洁、美观的主题！

---

**Comment by liuyib** [comment]
@wxdrizzle 你好，目前我没有太多精力维护 Stun 主题了，欢迎你贡献代码，我负责 Code Review ❤️

**Comment by wxdrizzle** [comment]
好的，有空我会提交pull request 😉
