### ISSUE TITLE
请问如何设置markdown的引用块背景颜色，默认是灰色想改成浅蓝色

### ISSUE THREAD

**Issue by qiangqQIANGQ** [liuyib/hexo-theme-stun#217]
![image](https://user-images.githubusercontent.com/73600117/127768481-5119d760-6429-446d-a0ac-6acd90b47b86.png)
## 我想创建一个新的 issue

- [] 是的，我已经阅读了 [常见问题](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md)。
- [] 是的，我已经阅读了 [Stun 的文档](https://theme-stun.github.io/docs/)。

## 实际行为

![image](https://user-images.githubusercontent.com/73600117/127768481-5119d760-6429-446d-a0ac-6acd90b47b86.png)## 其他信息

---

**Comment by liuyib** [comment]
在文档里搜索 自定义样式 就知道啦：
![image](https://user-images.githubusercontent.com/38221479/127880063-cda0d175-84db-4699-b996-3ad6f23a2007.png)
