### ISSUE TITLE
请问如何添加像你的主页那样的body背景图片,好看的彩带，并且点击还可以切换，谢谢

### ISSUE THREAD

**Issue by qiangqQIANGQ** [liuyib/hexo-theme-stun#218]
## 我想创建一个新的 issue

- [] 是的，我已经阅读了 [常见问题](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md)。
- [] 是的，我搜索并阅读了 [Issues 列表](https://github.com/liuyib/hexo-theme-stun/issues)（包括关闭的），但是没有帮助到我。
- [] 是的，我是第一次使用 Stun 主题。
- [] 是的，我之前用过 Stun 主题，并且可以正常运行。但是当我做了一些更改后，主题就无法正常运行了。
- [] 是的，我使用了 [平滑升级](https://theme-stun.github.io/docs/zh-CN/advanced/advanced.html#%E5%B9%B3%E6%BB%91%E5%8D%87%E7%BA%A7) 的特性，并且阅读了其文档。

## 环境信息

**Stun 版本：**

**Hexo 版本：**

**平台信息:**

**浏览器信息:**

**Node.js 和 NPM 版本：**

**NPM 依赖信息：**

**Hexo 配置信息：**

<details>
<summary>查看代码 ...</summary>

```yml

```
</details>

**Stun 配置信息：**

<details>
<summary>查看代码 ...</summary>

```yml

```
</details>

## 预期行为
![image](https://user-images.githubusercontent.com/73600117/127768682-ab3be4dd-bc1d-445a-965f-557cb0911820.png)

## 重现步骤

1. xxx
2. xxx
3. xxx

## 其他信息

---

**Comment by naumy-code** [comment]
同问。

**Comment by liuyib** [comment]
在配置文件里搜索：canvas_ribbon 就能找到了。这个功能在文档这里：https://theme-stun.github.io/docs/zh-CN/advanced/third-part.html#ribbon

主题的所有功能，文档里其实都有提到的 :heart:
