### ISSUE TITLE
脚注失效

### ISSUE THREAD

**Issue by 0ojixueseno0** [liuyib/hexo-theme-stun#22]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:v1.5.4.** 

**Hexo Version:v3.9.0.|** 

**Platform:Windows** 

**Browser:Chrome** 

## Expected behaviour 
使用脚注[^1] ，点击后到脚注锚点

## Actual behaviour 

脚注在博客中会识别成链接，跳转到/文章/脚注内容处

## Steps to reproduce the behaviour 
在文章中添加脚注即可

## Feature Request 

---

**Comment by liuyib** [comment]
我这边测试是没问题的，麻烦提供下 hexo 根目录下 package.json 文件的内容截图。

**Comment by 0ojixueseno0** [comment]
> @0ojixueseno0 麻烦提供下 hexo 根目录下 package.json 文件的内容截图。

抱歉，我在装插件之后忘记了hexo clear，现已自行解决，另请问如何给文章加上密码，不是很懂pug文件的语法，网络上的教程仅支持更改swig文件内容

**Comment by liuyib** [comment]
文章加密，有个比较好的插件 [hexo-blog-encrypt](https://github.com/MikeCoder/hexo-blog-encrypt) 你可以尝试用一下，pug 语法挺简单的，看下文档差不多就能上手了。后面 hexo-theme-stun 主题会集成一下文章加密的功能~

**Comment by 0ojixueseno0** [comment]
Thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liuyib"<notifications@github.com&gt;; 
发送时间: 2019年12月1日(星期天) 晚上6:03
收件人: "liuyib/hexo-theme-stun"<hexo-theme-stun@noreply.github.com&gt;; 
抄送: "2773173293"<jz0ojiang@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [liuyib/hexo-theme-stun] 脚注失效 (#22)




文章加密，有个比较好的插件 hexo-blog-encrypt 你可以尝试用一下，pug 语法挺简单的，看下文档差不多就能上手了。后面 hexo-theme-stun 主题会集成一下文章加密的功能~
