### ISSUE TITLE
首页分页按钮显示异常

### ISSUE THREAD

**Issue by coortop** [liuyib/hexo-theme-stun#23]
![QQ截图20191206193812](https://user-images.githubusercontent.com/49756728/70321751-23392d00-1863-11ea-9b73-bea8411fb039.png)
![QQ截图20191206195518](https://user-images.githubusercontent.com/49756728/70321752-23392d00-1863-11ea-9a0c-556bd3efe9c3.png)
![QQ截图20191206195542](https://user-images.githubusercontent.com/49756728/70321755-23d1c380-1863-11ea-9a0a-c135e9a0150d.png)
这里的<被解析成& lt;了
![QQ截图20191206200208](https://user-images.githubusercontent.com/49756728/70321813-54196200-1863-11ea-9749-926cf33e5960.png)

**Comment by liuyib** [comment]
你的hexo版本应该是4.0.0的吧? 把主题更新到最新版就好了。这是 hexo 进行 breaking change 更新引起的，这个问题前面有人提了issue: https://github.com/liuyib/hexo-theme-stun/issues/20。


 
---原始邮件---
发件人: "coortop"<notifications@github.com&gt;
发送时间: 2019年12月6日 20:04:42
收件人: "liuyib/hexo-theme-stun"<hexo-theme-stun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [liuyib/hexo-theme-stun] 首页分页按钮显示异常 (#23)




 
 
 这里的<被解析成&amp; lt;了

**Comment by coortop** [comment]
谢谢，已解决
