### ISSUE TITLE
执行 hexo s 命令后报错，无法启动

### ISSUE THREAD

**Issue by SeiFujibayashi** [liuyib/hexo-theme-stun#25]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** 1.5.4

**Hexo Version:** 4.2.0

**Platform:** Windows

**Browser:** Chrome

## Actual behaviour 
【Tonight I deleted all the commits from my blog repo, but I don't think this should be the main reason. Then when I upgraded HEXO to 4.2.0 and typed HEXO S, this happened:】

【今晚我将我的博客repo的commits全部删除了，不过我认为这个应该不是主要原因。随后当我将HEXO的升级至4.2.0并且键入HEXO S时出现了这样的情况：】

![图片](https://github.com/SeiFujibayashi/BlogImage/raw/master/Issue.png)

【This does not happen with the official default theme "landscape". I tried to init HEXO and reset it according to the [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/), but it didn't work.】
【使用官方默认主题“landscape”则不会出现这种情况，我尝试初始化HEXO并按照[中文文档](https://liuyib.github.io/hexo-theme-stun/zh-CN/)进行重新设置，但是不起作用。】

## Feature Request 

---

**Comment by liuyib** [comment]
@SeiFujibayashi stun 主题里的 tag plugins 部分代码中，依赖于 cheerio 这个库，在 hexo 4.0 中它是 `dependencies` 依赖，会随着 hexo 一起安装，而在 hexo 4.2 中，它变成了 `devdependencies` 依赖，默认不会安装。因此使得 stun 主题无法运行，我会用最快的时间，修复这个问题。

**Comment by liuyib** [comment]
@SeiFujibayashi  问题已解决：[#25](https://github.com/liuyib/hexo-theme-stun/commit/d30e33f15be16c09cb5cd2789079ea304f4c398a)，使用命令：`git pull origin dev` 更新一下主题就可以了，过几天会发布新版本。

**Comment by SeiFujibayashi** [comment]
> @SeiFujibayashi 问题已解决：[#25](https://github.com/liuyib/hexo-theme-stun/commit/d30e33f15be16c09cb5cd2789079ea304f4c398a)，使用命令：`git pull origin dev` 更新一下主题就可以了，过几天会发布新版本。

我已经更新至git pull到最新版本了，然后设置完_config以后在启动服务器时它又显示这个：

![issue](https://github.com/SeiFujibayashi/BlogImage/raw/master/issue2.png)

**Comment by liuyib** [comment]
@SeiFujibayashi  你是执行的 `git pull origin dev` 吗，因为我只把修改的代码推到了 dev 分支上，还没有合并到 master 分支，所以如果你是执行的 `git pull` 或 `git pull origin master` 是不行的。而且我修改了代码之后 Stun 主题已经不依赖 `cheerio` 这个库了，你再确认一下~

**Comment by SeiFujibayashi** [comment]
> @SeiFujibayashi 你是执行的 `git pull origin dev` 吗，因为我只把修改的代码推到了 dev 分支上，还没有合并到 master 分支，所以如果你是执行的 `git pull` 或 `git pull origin master` 是不行的。而且我修改了代码之后 Stun 主题已经不依赖 `cheerio` 这个库了，你再确认一下~ 如果还不行，你可以更新一下 hexo-cli 后再尝试~ 如果还有问题，再告诉我一下，感谢🙌

噢不好意思，是我搞错了，现在好了，感谢帮助！
还有就是我将代码高亮主题改成**dark**或者**ocean**以后其样式并没有改变，即高亮主题仍然是**light**，我清除了浏览器缓存重新加载也没用……还请帮忙看下是什么问题
另外右上角那个夜间模式感觉很棒！

**Comment by liuyib** [comment]
@SeiFujibayashi  我试了下，切换代码高亮后，主题仍然是 light，这个是添加夜间模式功能的时候引起的一个 bug，我会尽快修复。等最近修改的功能都测试之后，会发布新版本，到时候更新到最新版就行了~ 感谢反馈！
