### ISSUE TITLE
valine评论问题

### ISSUE THREAD

**Issue by coortop** [liuyib/hexo-theme-stun#26]
**Stun Version:** 1.5.4

**Hexo Version:** 4.0.0

问题：
开启pjax，切换页面评论不刷新成当前页面的评论

**Comment by liuyib** [comment]
验证了下，确实存在这个问题，会尽快修复，感谢反馈~

**Comment by coortop** [comment]
之前我以为关不掉评论验证也是问题，最后查到开启邮箱通知自动开启评论验证，然后我就把邮箱通知关了就好了

**Comment by liuyib** [comment]
> 之前我以为关不掉评论验证也是问题，最后查到开启邮箱通知自动开启评论验证，然后我就把邮箱通知关了就好了,如果需要使用邮箱通知，建议使用Valine-Admin
> https://github.com/ZvonimirSun/Valine-Admin

可以，后面会考虑把 Valine-Admin 整合到主题中，然后提供配置项。感谢建议~

**Comment by liuyib** [comment]
启用 pjax 后，切换页面评论不刷新的问题已解决，见 PR：https://github.com/liuyib/hexo-theme-stun/pull/27
