### ISSUE TITLE
标题分级显示错误

### ISSUE THREAD

**Issue by SeiFujibayashi** [liuyib/hexo-theme-stun#28]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** 1.6.0、1.5.4

**Hexo Version:** 4.2.0

**Platform:** Windows

**Browser:** Chrome

## Actual behaviour 

在本地编辑MD文件的时候利用Markdown语法书写标题：![标题分级无效（1）](https://user-images.githubusercontent.com/16505813/73077267-d1c02c80-3efa-11ea-8115-e0af3fdd4230.jpg)
【Use the Markdown syntax to write the title when editing the MD file locally:】

但是在网页中却没有达到理想的效果：
![标题分级无效（2）](https://user-images.githubusercontent.com/16505813/73077296-de448500-3efa-11ea-953e-1e2eccf0e75d.jpg)
【But in the web page, it did not achieve the desired effect:】

这个问题在我上次 git pull origin dev  的时候应该就出现了。
【This problem should have occurred when I last git pull origin dev.】

## Feature Request 

---

**Comment by liuyib** [comment]
看了下，这个是上次版本更新时引入的一个 bug（只有 1.6.0 版本有），已修复：[#28](https://github.com/liuyib/hexo-theme-stun/commit/8a9ca0138dc95163b575b3f98bd513a6473e97e0)。感谢反馈~
