### ISSUE TITLE
不蒜子统计启动后出现重复统计

### ISSUE THREAD

**Issue by 1021263881** [liuyib/hexo-theme-stun#31]
- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

**Stun Version:** 1.7.0

**Hexo Version:** 4.2.0

**Platform:** Linux 

**Browser:** Chrome 

每次打开文章或者是刷新网页，文章浏览数和网站总浏览数都+2了，而不是+1。

在我注释掉`layout\_layout.pug`中的两行`include ./_third-party/analytics/busuanzi.pug`情况得到解决。感觉上像是`layout\_layout.pug`和`layout\_partials\footer\footer.pug`重复添加不蒜子js链接造成的访问重复？

两个js的回调顺序有时候会反过来，浏览数会先+2然后-1，大概是网络问题罢

**Comment by liuyib** [comment]
问题已修复：[8198d5a](https://github.com/liuyib/hexo-theme-stun/commit/8198d5a284a785b4cc22431d610d0d612bbdff43)，确实引入了重复的 busuanzi 脚本，感谢反馈
