### ISSUE TITLE
版本升级之后配置文件失效？

### ISSUE THREAD

**Issue by woyasuohen6** [liuyib/hexo-theme-stun#33]
一开始我用的 1.6.0 版本。
后来更新到 1.7.0 ，以前的配置文件全部失效了，复制过去会报错。

**Comment by liuyib** [comment]
你是不是使用了[平滑升级](https://liuyib.github.io/hexo-theme-stun/zh-CN/advanced/advanced-setting.html#%E5%B9%B3%E6%BB%91%E5%8D%87%E7%BA%A7)这一特性，在 `/source/_data/` 目录下新建了 `stun.yml` 文件？如果是的话，有没有将这个文件里的配置项和主题目录下的 `_config.yml` 同步呢？

**Comment by woyasuohen6** [comment]
一开始我没有使用平滑升级这一特性。
后来使用了这个特性，解决了问题。

**Comment by liuyib** [comment]
@woyasuohen6 你是把以前的配置文件直接复制过去的？主题更新之后配置文件里的配置项**可能会**有所更改，如果配置项有所更改我会在版本发布时指出来，比如：[v1.7.0](https://github.com/liuyib/hexo-theme-stun/releases/tag/v1.7.0)。所以，你不能为了保留配置的数据而直接把以前的配置文件的内容复制过去。利用平滑升级特性也就可以解决问题~
