### ISSUE TITLE
部署到GitHub上时候，顶部背景图片无法正常显示。

### ISSUE THREAD

**Issue by lNeverl** [liuyib/hexo-theme-stun#35]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** 
1.7.0

**Hexo Version:** 
4.2.0

**Platform:** 
Windows

**Browser:** 
Chrome 

## Actual behaviour 
部署到GitHub上时候，顶部背景无法正常显示，但是在本地http://localhost:4000/上查看可以正常显示，路径用的是在hexo根目录下的/pic/cover1.jpg。在主题根目录下的source/images也尝试过，同样是部署后无法显示，本地可以正常显示，

## Feature Request 

---

**Comment by liuyib** [comment]
@lNeverl 提供的信息太少，没办法定位问题。你需要让我看看：1. 你的目录结构截图（要看见你引用的图片所在的完整目录）2. 你在主题配置文件中配置的顶部图片路径 3. 部署之后，在浏览器地址栏手动输入你引用图片的路径，看是否能找到

**Comment by lNeverl** [comment]
我也不清楚为什么莫名其妙问题消失了。非常感谢您的解答，之后有问题，或者发现这次问题的原因，我会在来这里更新的。

**Comment by CodeRainjzw** [comment]
我也遇见了相同的问题，
![US{Y1CSZK6NP( 5MBX (DN8](https://user-images.githubusercontent.com/72017670/94444617-17936a00-01d9-11eb-87ec-ec543e9dcb19.png)
部署完后本地正常显示，但gitee的page就无法显示顶部和背景

另外，请问本地图片路径怎么设置？它的格式是什么？（我按照file:///... 和直接/images/name.jpg都试过了 本地都无法加载图片）

**Comment by liuyib** [comment]
我看你这设置的是引用新浪的图片，人家要是设置防盗链你当然不能访问了。
本地图片的引用路径文档里有。


 
---原始邮件---
发件人: "CodeRainjzw"<notifications@github.com&gt;
发送时间: 2020年9月28日 22:26:14
收件人: "liuyib/hexo-theme-stun"<hexo-theme-stun@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"liuyib"<1656081615@qq.com&gt;;
主题: Re: [liuyib/hexo-theme-stun] 部署到GitHub上时候，顶部背景图片无法正常显示。 (#35)




 
我也遇见了相同的问题，
 
 部署完后本地正常显示，但gitee的page就无法显示顶部和背景
 
另外，请问本地图片路径怎么设置？它的格式是什么？（我按照file:///... 和直接/images/name.jpg都试过了 本地都无法加载图片）

**Comment by CodeRainjzw** [comment]
您是指控制文档里注释表示的那样吗，我按照绿字那样，自己理解尝试了以下三种路径写法都不行。。
![image](https://user-images.githubusercontent.com/72017670/94447046-f3855800-01db-11eb-9c69-1a196b4af330.png)
![image](https://user-images.githubusercontent.com/72017670/94447313-347d6c80-01dc-11eb-957f-64f2f7ce90ac.png)
![image](https://user-images.githubusercontent.com/72017670/94447375-43641f00-01dc-11eb-8780-d671c9aa8679.png)

**Comment by liuyib** [comment]
https://theme-stun.github.io/docs
这是文档地址，你先看下，应该能解决你的问题。
 
---原始邮件---
发件人: "CodeRainjzw"<notifications@github.com&gt;
发送时间: 2020年9月28日 22:45:49
收件人: "liuyib/hexo-theme-stun"<hexo-theme-stun@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"liuyib"<1656081615@qq.com&gt;;
主题: Re: [liuyib/hexo-theme-stun] 部署到GitHub上时候，顶部背景图片无法正常显示。 (#35)




 
您是指控制文档里注释表示的那样吗，我按照绿字那样，自己理解尝试了以下三种路径写法都不行。。

**Comment by CodeRainjzw** [comment]
抱歉，请原谅我的愚笨，我将图片文件放在了hexo根目录的sourse里，并按照文档中直接/header.jpg引用了，但仍然无法加载。。
![image](https://user-images.githubusercontent.com/72017670/94450069-647a3f00-01df-11eb-8eb2-cf477b1a657c.png)
![image](https://user-images.githubusercontent.com/72017670/94450293-aa370780-01df-11eb-9237-9b20d70ad183.png)

**Comment by liuyib** [comment]
我在坐车，晚些回复你


 
---原始邮件---
发件人: "CodeRainjzw"<notifications@github.com&gt;
发送时间: 2020年9月28日 23:13:14
收件人: "liuyib/hexo-theme-stun"<hexo-theme-stun@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"liuyib"<1656081615@qq.com&gt;;
主题: Re: [liuyib/hexo-theme-stun] 部署到GitHub上时候，顶部背景图片无法正常显示。 (#35)




 
抱歉，请原谅我的愚笨，我将图片文件放在了hexo根目录的sourse里，并按照文档中直接/header.jpg引用了，但仍然无法加载。。

**Comment by CodeRainjzw** [comment]
抱歉？怕您忘了，不知道您对我上面描述的这个问题有思路嘛？

**Comment by liuyib** [comment]
@CodeRainjzw 你执行一下 `hexo g` 指令，看下 `src/public` 目录下，有没有你这个 `header.jpg` 文件？

**Comment by liuyib** [comment]
@CodeRainjzw  如果有，你在网页中找到这个 HTML 元素和它的 CSS 属性：
![image](https://user-images.githubusercontent.com/38221479/94574163-673f6780-02a5-11eb-8e8d-a660ed4faba7.png)

**Comment by CodeRainjzw** [comment]
![image](https://user-images.githubusercontent.com/72017670/94580453-88f01d00-02ac-11eb-99ff-fda7e284968f.png)

它还显示not found the picture
![image](https://user-images.githubusercontent.com/72017670/94580625-b89f2500-02ac-11eb-90a6-295bb572a1f6.png)

**Comment by liuyib** [comment]
@CodeRainjzw  你有没有执行一下 `hexo g` 指令，看下 `src/public` 目录下，有没有你这个 `header.jpg` 文件？
另外，我可以明确告诉你，这个图片你放置了却找不到，和主题没有任何关系（主题只是按照你设置的 路径 去显示）
而且，你看现在反馈给我的信息没法定位问题，你需要尽可能多的反馈给我信息（你的 hexo 
 的 package.json、hexo 的 _config.yml 文件、等等，把你觉着可能的、有用的信息都反馈给我），不止是我让你做的。

**Comment by CodeRainjzw** [comment]
本地的图片如何加载我还是不清楚怎么解决，但是我现在通过清除浏览器缓存 重新部署，用通过在线图片的方式成功了，先谢谢了，本地的以后我再自己研究一下好了。

**Comment by liuyib** [comment]
👌🏻👌🏻👌🏻


 
---原始邮件---
发件人: "CodeRainjzw"<notifications@github.com&gt;
发送时间: 2020年9月30日 19:23:48
收件人: "liuyib/hexo-theme-stun"<hexo-theme-stun@noreply.github.com&gt;;
抄送: "Comment"<comment@noreply.github.com&gt;;"liuyib"<1656081615@qq.com&gt;;
主题: Re: [liuyib/hexo-theme-stun] 部署到GitHub上时候，顶部背景图片无法正常显示。 (#35)




 
本地的图片如何加载我还是不清楚怎么解决，但是我现在通过清除浏览器缓存 重新部署，用通过在线图片的方式成功了，先谢谢了，本地的以后我再自己研究一下好了。
