### ISSUE TITLE
顶部图mask属性在deploy时无法成功应用

### ISSUE THREAD

**Issue by Megumism** [liuyib/hexo-theme-stun#36]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** 
1.7.0

**Hexo Version:** 
hexo: 4.2.0
hexo-cli: 3.1.0

**Platform:**
os: Windows_NT 10.0.18362 win32 x64

**Browser:** 
Chrome

## Actual behaviour 

运行`hexo s`，在本地顶部图mask是可以正常显示的。
但`hexo d`部署到GitHub page之后无法显示。
已经尝试过多次`hexo clean && hexo g`。

![898fWF.png](https://s2.ax1x.com/2020/03/09/898fWF.png)
![898WJU.png](https://s2.ax1x.com/2020/03/09/898WJU.png)

## Feature Request 

---

**Comment by liuyib** [comment]
@Megumism  我去你的博客看了下，完全没问题啊。你是浏览器有缓存吧？

**Comment by Megumism** [comment]
没事了（捂脸）打扰了打扰了
