### ISSUE TITLE
文章字数过少时自动保留摘要最后会出现document.querySele......

### ISSUE THREAD

**Issue by mykahei** [liuyib/hexo-theme-stun#37]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** 1.7.0

**Hexo Version:** 4.0.0

**Platform:** Windows

**Browser:** Chrome

## Expected behaviour 

首页正常显示每篇文章自动保留的150字摘要，若文章小于150字，则显示实际字数。

## Actual behaviour 

![Screen Shot 2020-03-10 at 16 04 32](https://user-images.githubusercontent.com/18681247/76292117-8e265400-62e9-11ea-8bb6-d45c7095adb7.png)

实际上文章到第三行已经结束，但摘要最后却包含了document.querySele......样子的代码

## Steps to reproduce the behaviour 

写一篇少于配置中自动保留摘要字数的文章

## Feature Request 

建议添加关于字数的判断

---

**Comment by liuyib** [comment]
@mykahei  这个自动保留摘要的功能确实不好用，而且这个功能仅仅是用偷懒的方法实现的，效果很差。另外，讲道理，这个功能不属于主题的范畴，它应该是 Hexo 插件要做的事。下个版本这个功能会被移除，建议手动添加 `<!-- more -->` 标记来设置文章摘要吧。
