### ISSUE TITLE
网页顶部图片无法显示，yml文件里已经添加了图片路径及true

### ISSUE THREAD

**Issue by zhangtaofred** [liuyib/hexo-theme-stun#4]
## I want to create a new issue 

- [] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** 

**Platform:** 

**Browser:** 

## Feature Request 

---

**Comment by liuyib** [comment]
有没有报错？有没有重启 hexo 服务器？如果你在 `source/_data/` 目录下拷贝了一份配置文件，那么你应该修改这里面的配置，而不是原来的那个 `_config.yml` 文件，前者会覆盖后者。

如果不是我说的上述原因，希望你再提供些必要信息。

**Comment by zhangtaofred** [comment]
>重启了。我没有那个data目录，

- 
![1](https://user-images.githubusercontent.com/53425107/62524429-319d1b00-b868-11e9-9762-b4d6329c3f89.jpg)
![2](https://user-images.githubusercontent.com/53425107/62524437-34980b80-b868-11e9-95a5-58bc47d6b53a.jpg)


__
1. 
![3](https://user-images.githubusercontent.com/53425107/62524440-3661cf00-b868-11e9-9316-bfc2b63256ed.jpg)

**Comment by liuyib** [comment]
![image](https://user-images.githubusercontent.com/38221479/62524797-d4ee3000-b868-11e9-844e-fee196d44749.png)

`.yml` 文件中，每行以 `#` 开头的是注释，你得把路径填到上图箭头指的地方才行。你再看下。

**Comment by zhangtaofred** [comment]
![Snipaste_2019-08-06_16-48-38](https://user-images.githubusercontent.com/53425107/62525471-1206f200-b86a-11e9-9513-997eb68bc69b.jpg)
ok，谢谢了第一次接触这些东西，不太懂，还有上图的警告需要理会解决吗

**Comment by liuyib** [comment]
这些警告似乎不是主题的。如果可以的话给个 star 😄。
如果还有其他问题，可以提新的 issue 或者 在 [gitter](https://gitter.im/liuyib/hexo-theme-stun?utm_source=share-link&utm_medium=link&utm_campaign=share-link) 直接交流，在 gitter 里交流更方便些。
