### ISSUE TITLE
Pagination of homepage article list

### ISSUE THREAD

**Issue by Sooling** [liuyib/hexo-theme-stun#41]
## Pagination of homepage article list 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version: 1.0.3以上** 

**Hexo Version: 4.2.0** 

**Platform: Window** 

**Browser: Edge、Chrome** 

## Expected behaviour 
The home page list is paged, and the value of home is set to true to achieve paging effect

## Actual behaviour 
There is no page break in the homepage article list

## Feature Request 
Do articles need to reach a certain number to realize paging function?
What's the quantity then?

---

**Comment by liuyib** [comment]
On the homepage, 10 articles are displayed by default, in Hexo `_config.yml`:
![snipaste20200328223321](https://user-images.githubusercontent.com/38221479/77825427-2b83e380-7144-11ea-9a6f-2fabfe1cdeab.png)
If the number of articles is less then this value, it will display：
![image](https://user-images.githubusercontent.com/38221479/77825442-566e3780-7144-11ea-8983-8434ebc5fcb7.png)

What is your problem, can you show me a screenshot?
