### ISSUE TITLE
无法使用标题下“阅读次数”特性

### ISSUE THREAD

**Issue by DDCHlsq** [liuyib/hexo-theme-stun#45]
在作者您提供的使用文档，以及主题配置_config.yml中均没有找到，故无法使用“阅读次数”特性。
能否告知如何使用该特性？

**Comment by liuyib** [comment]
这不是一个单独的特性，而是第三方插件提供的。有两个可以选择：

- 使用 Valine 评论，自带文章阅读次数统计。详见：[hexo-theme-stun docs valine](https://liuyib.github.io/hexo-theme-stun/zh-CN/advanced/third-part.html#valine)
   > 其中的 `visitor` 选项就是阅读次数。
- 使用 busuanzi 统计。详见：[hexo-theme-stun docs 卜蒜子统计](https://liuyib.github.io/hexo-theme-stun/zh-CN/advanced/third-part.html#卜蒜子统计)
   > 其中的 `post_pv` 选项就是阅读次数。

Stun 主题有考虑过，单独实现“阅读次数”这个功能（不过需要借助第三方存储服务）最近的版本中会加上，感谢支持，如果还有其他问题尽管提问 🙌

**Comment by DDCHlsq** [comment]
感谢解惑
