### ISSUE TITLE
怎样更改单个标签显示页的每页显示文章数/How can I modify to change the number of articles displayed on each page of a single tag display page

### ISSUE THREAD

**Issue by cjh0613** [liuyib/hexo-theme-stun#49]
请问修改哪些代码可更改单个标签显示页的每页显示文章数？

How can I modify to change the number of articles displayed on each page of a single tag display page?

![image](https://user-images.githubusercontent.com/25498029/78538906-50ebae00-7824-11ea-9ac9-39624522d3c5.png)

**Comment by cjh0613** [comment]
默认每页10项标题，我想修改一下

10 titles per page by default, I want to modify it.

**Comment by liuyib** [comment]
这个目前还不能修改，之前也没考虑到，既然有这个需求，下个版本我加一下，会提供配置项给用户进行配置。


 
---原始邮件---
发件人: "cjh0613"<notifications@github.com&gt;
发送时间: 2020年4月6日 16:43:42
收件人: "liuyib/hexo-theme-stun"<hexo-theme-stun@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [liuyib/hexo-theme-stun] 怎样更改单个标签显示页的每页显示文章数/How can I modify to change the number of articles displayed on each page of a single tab display page (#49)




 
默认每页10项标题，我想修改一下
 
10 titles per page by default, I want to modify it.

**Comment by cjh0613** [comment]
Did not continue the discussion for a long time, close
