### ISSUE TITLE
How to use picture in local directory

### ISSUE THREAD

**Issue by Gunmx** [liuyib/hexo-theme-stun#5]
How to use the gallery(photo album)?

**Comment by liuyib** [comment]
See the doc: [https://liuyib.github.io/hexo-theme-stun/zh-CN/advanced/theme-config.html#front-matter](https://liuyib.github.io/hexo-theme-stun/zh-CN/advanced/theme-config.html#front-matter)。

You can use `photos` in the front-matter of post / page. For details, you can see the doc. 🤗

**Comment by Gunmx** [comment]
I want to know how to upload my photos and which file there should be placed. Thank you.

**Comment by liuyib** [comment]
Placing photos to `themes/stun/source/images/` or create a new folder in `/source/` in your site root directory.

Such as:
![image](https://user-images.githubusercontent.com/38221479/62748223-6a1c3f00-ba8a-11e9-80c0-1024d1599fb6.png)
After run `hexo g`, it will generate:
![image](https://user-images.githubusercontent.com/38221479/62748248-891ad100-ba8a-11e9-8e2a-53184071b5ee.png)
Then you can use it: `/imgs/stun-logo.png`.
