### ISSUE TITLE
你好，如何更换主题封面

### ISSUE THREAD

**Issue by DNMWSEA** [liuyib/hexo-theme-stun#64]
## I want to create a new issue 

- [] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** 

**Hexo Version:** 

**Platform:** 

**Browser:** 

## Feature Request 

---

**Comment by DNMWSEA** [comment]
想修改themes/stun的封面，请指教

**Comment by liuyib** [comment]
@DNMWSEA 你指的是顶部大图吗？如果是的话，修改主题配置文件中的 `header` 下的 `bg_image`；你还可以给每篇文章或每个页面单独设置，文档里有说明：[指定顶部图](https://liuyib.github.io/hexo-theme-stun/zh-CN/guide/primary-setting.html#%E6%8C%87%E5%AE%9A%E9%A1%B6%E9%83%A8%E5%9B%BE)。

建议通读一遍文档，对使用很有帮助。如果没有时间，把文档中[【新手上路】](https://liuyib.github.io/hexo-theme-stun/zh-CN/guide/primary-setting.html#%E6%96%B0%E6%89%8B%E4%B8%8A%E8%B7%AF)部分阅读一遍就可以了。

感谢支持！

**Comment by liuyib** [comment]
如果还有问题就继续追问，也可以加 Q 群 1019013440。没有问题的话，就把 Issue 关了吧。

**Comment by DNMWSEA** [comment]
Thank you ，建议很好



---原始邮件---
发件人: "liuyib"<notifications@github.com&gt;
发送时间: 2020年5月2日(周六) 下午4:41
收件人: "liuyib/hexo-theme-stun"<hexo-theme-stun@noreply.github.com&gt;;
抄送: "Mention"<mention@noreply.github.com&gt;;"DNMWSEA"<962613283@qq.com&gt;;
主题: Re: [liuyib/hexo-theme-stun] 你好，如何更换主题封面 (#64)




 
Closed #64.

**Comment by DNMWSEA** [comment]
好的，关掉它



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "liuyib"<notifications@github.com&gt;; 
发送时间: 2020年5月2日(星期六) 上午10:17
收件人: "liuyib/hexo-theme-stun"<hexo-theme-stun@noreply.github.com&gt;; 
抄送: "鹏"<962613283@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [liuyib/hexo-theme-stun] 你好，如何更换主题封面 (#64)





 
如果还有问题就继续追问，也可以加 Q 群 1019013440。没有问题的话，就把 Issue 关了吧。
