### ISSUE TITLE
KaTex(hexo-renderer-markdown-it-plus) error. 启用KaTex公式后的错误

### ISSUE THREAD

**Issue by cjh0613** [liuyib/hexo-theme-stun#65]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:**  v1.7.0

**Hexo Version:** 4.2.0

**Platform:** Windows / Linux

**Browser:** All

package.json
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.2.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-admin": "^2.3.0",
    "hexo-autonofollow": "^1.0.1",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-baidu-sitemap": "^0.1.6",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-sitemap": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-render-pug": "^2.1.4",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-markdown-it-plus": "^1.0.4",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-tag-dplayer": "^0.3.3",
    "hexo-wordcount": "^6.0.1",
    "lazyload": "^2.0.0-rc.2"
  }
}
```

## Actual behaviour 

1. After I run `npm un hexo-renderer-marked --save`and`npm i hexo-renderer-markdown-it-plus --save`
The KaTex can't display successfully.
link: https://cjh0613.gitee.io/blog/20200502Electrotechnics1.html 

~~2. I can't `hexo server` successfully as usual.~~（solved）
error page link: https://cjh0613.gitee.io/blog/20200402HexoTagPlugins.html
IN git-bash:
```
Nunjucks Error:  [Line 5, Column 4] unknown block tag: note
    =====               Context Dump               =====
    === (line number probably different from source) ===
  1 | <p>标签插件和 Front-matter 中的标签不同，它们是用于在文章中快速插入特定内容的插件。</p>
  2 | <p><a href="https://hexo.io/zh-cn/docs/tag-plugins.html">https://hexo.io/zh-cn/docs/tag-plugins.html</a></p>
  3 | <!-- more -->
  4 | <h2 id="插入注释-badge-textstable-badge-textv120"><a class="markdownIt-Anchor" href="#插入注释-badge-textstable-badge-textv120"></a> 插入注释 <Badge text="Stable"/> <Badge text="v1.2.0"/></h2>
  5 | {% note warning no-icon %}
  6 | **info** 类型的标注从 `v2.0.0-rc.0` 开始支持，其他类型的标注均从 `v1.2.0` 开始支持。
  7 | {% endnote %}

```

## Feature Request 

---

**Comment by liuyib** [comment]
@cjh0613 About Katex, Have you set the following? 
![image](https://user-images.githubusercontent.com/38221479/80896556-1b9e8700-8d22-11ea-9673-c608aac55e81.png)

**Comment by liuyib** [comment]
@cjh0613  About the error `Nunjucks Error:  [Line 5, Column 4] unknown block tag: note`, it is maybe caused by some Markdown syntax errors. e.g. Front-Matter is missing from your Markdown file.

**Comment by cjh0613** [comment]
> @cjh0613 About Katex, Have you set the following?
> ![image](https://user-images.githubusercontent.com/38221479/80896556-1b9e8700-8d22-11ea-9673-c608aac55e81.png)

Thanks.  

And the No.2 error is caused by some files of hexo have not been copied when I  use  another computer to deploy.
