### ISSUE TITLE
search window does not appear when hit search button

### ISSUE THREAD

**Issue by tannineo** [liuyib/hexo-theme-stun#68]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** 2.0.0

Well.. actually:
- commit: 67b095bfc5167990f723b824b6e87db2be669fd9
- comment: chore: Modify the config for docs
- on master branch

**Hexo Version:** 4.2.0

**Platform:** macOS

**Browser:** Chrome

## Expected behaviour 

I am using the local-search feature: https://liuyib.github.io/hexo-theme-stun/zh-CN/advanced/third-part.html#%E6%9C%AC%E5%9C%B0%E6%90%9C%E7%B4%A2

Search window should appear when I hit the search button.

## Actual behaviour 

Search window DOSE NOT appear when I hit search button.

![image](https://user-images.githubusercontent.com/33346345/81455753-03968f80-9188-11ea-989d-1cef68d57e3f.png)

## Steps to reproduce the behaviour 

I found that the search button won't work on the pages, but it works well in the blog post.

You can access my blog on github page here: https://tannineo.github.io/
Or check the source code on branch `source` in this repo: https://github.com/tannineo/tannineo.github.io

## Feature Request 

---

**Comment by liuyib** [comment]
In your repository [https://github.com/tannineo/tannineo.github.io](https://github.com/tannineo/tannineo.github.io), the stun folder is not pushed up, you can perform the following steps:

1. Add `themes/*/.git` to the `.gitignore` file in the root directory of hexo.
2. **Re-download the Stun theme** or **run `git rm -r --cached .\themes\stun\` in the root directory of hexo**.

I can't find the problem for the moment, and I will reply to you when I have time.

**Comment by tannineo** [comment]
There are no change to the code under `theme/stun`, you can check the commit: 67b095bfc5167990f723b824b6e87db2be669fd9

The config file is in `source/_data/`

**Comment by tannineo** [comment]
@liuyib And thank you for your reply.
Now I pushed the code in `themes/stun/`
The code is downloaded by a zip from master branch

**Comment by liuyib** [comment]
In https://github.com/liuyib/hexo-theme-stun/commit/67b095bfc5167990f723b824b6e87db2be669fd9，That is the `config.js` for docs. It has nothing to do with your problem.

**Comment by tannineo** [comment]
@liuyib Thanks, I see...
I just mean the code is from the newest master branch.

**Comment by liuyib** [comment]
I have seen your repo, why did you use the plugin `hexo-inject`? I guess your problem may be related to it.

Some people have had the same problem with the `hexo-inject` plugin. You can try to uninstall `hexo-inject` and restart hexo, then give me a callback.

**Comment by tannineo** [comment]
@liuyib Thank you!
Removing `hexo-inject` really helps.
It's a remaining dependency from my test on other themes. orz
The problem solved.
Perhaps adding this as a warning to the document or FAQ?

**Comment by liuyib** [comment]
I need to find what conflicts between stun and `hexo-inject`, and try to solve them. Thanks for your issue.

**Comment by liuyib** [comment]
FAQ has been added, see: https://github.com/liuyib/hexo-theme-stun/blob/dev/FAQ.md#%E7%82%B9%E5%87%BB%E6%90%9C%E7%B4%A2%E6%8C%89%E9%92%AE%E6%B2%A1%E6%9C%89%E4%BB%BB%E4%BD%95%E5%8F%8D%E5%BA%94

hexo-inject has been deprecated, so there is no need to compatible. now this issue can be closed.
