### ISSUE TITLE
怎么让主题的代码高亮？

### ISSUE THREAD

**Issue by skywingfs** [liuyib/hexo-theme-stun#7]
所有的代码都是灰色的，没有高亮，请问下怎么设置呀？

**Comment by liuyib** [comment]
主题默认是有代码高亮的，你可以再提供一些必要的信息吗? 比如，你的 markdown 文件内容截图

**Comment by skywingfs** [comment]
我将配置文件的auto_detect改为true后，有高亮了，但有些语言似乎识别有问题，php被识别为了xml，能把highlightjs这种集成进博客么~
![image](https://user-images.githubusercontent.com/12905834/63590437-64703e80-c5de-11e9-8184-2bf05f0cdc3b.png)

**Comment by liuyib** [comment]
主题可以集成 highlightjs，但是有点多余，Hexo 自带的代码高亮功能基本够用，你最好是手动设置代码的语言，像这样：
![image](https://user-images.githubusercontent.com/38221479/63596899-d81a4780-c5ee-11e9-9be8-94618e3d9dc9.png)
通常我们嵌入代码的时候，都要自己指定语言。现阶段主题还没有集成 highlightjs 的打算，并且即便是 highlightjs，自动检测语言也会有偏差，所以最好的办法就是自己手动指定语言即可。

**Comment by skywingfs** [comment]
好的呢，谢谢啦~
