### ISSUE TITLE
关于首页的ReadMore按钮

### ISSUE THREAD

**Issue by skywingfs** [liuyib/hexo-theme-stun#8]
关于首页每篇文章的ReadMore按钮，就是文章无论多长都会在首页全部加载，这个readmore按钮似乎没啥意义，怎么能调整下，让首页每篇文章只展示部分，谢谢！
![image](https://user-images.githubusercontent.com/12905834/63632261-67624200-c665-11e9-9232-651593776143.png)

**Comment by liuyib** [comment]
这算是一个小问题吧，不过有些争议，原因如下：首页显示的是文章摘要，你需要在文章的 markdown 源文件中手动添加 `<!-- more -->` 标记来设置摘要截取的长度（关于摘要的设置可以参考文档：[文章摘要](https://liuyib.github.io/hexo-theme-stun/zh-CN/advanced/theme-config.html#%E6%96%87%E7%AB%A0%E6%91%98%E8%A6%81)）。如果用户没有手动设置那个标记的话，那么在首页到底是不显示文章内容，还是全部显示，或者自动截取前几百字进行显示，对于这几种做法，我选择了全部显示，感觉这样会更合理些，我参考了大多数主题，也都是全部显示。

所以，总结一下：

- 主题默认情况下，在首页显示全部文章内容
- 如果想在首页显示部分文章内容，需要用户手动设置 `<!-- more -->` 标记（这是 Hexo 要求的，与主题无关）
- 如果想要主题自动保留文章的前几百字文字作为摘要，可以参考文档进行设置：[文章摘要](https://liuyib.github.io/hexo-theme-stun/zh-CN/advanced/theme-config.html#%E6%96%87%E7%AB%A0%E6%91%98%E8%A6%81)

回头我会调整下 `readmore` 按钮的显示情况，让其默认情况下不显示，只有设置了摘要的情况下才会显示。

**Comment by skywingfs** [comment]
好的，谢谢！之前没看主题配置文档，现在要好好看下了。
