### ISSUE TITLE
将博客部署到gitee上出现跨域问题，点击其他页面没有反应

### ISSUE THREAD

**Issue by lienhui68** [liuyib/hexo-theme-stun#82]
## 将博客部署到gitee上出现跨域问题，点击其他页面没有反应

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information
**Stun Version:** 2.0.1
**Hexo Version:** 4.2.1
**Platform:** macOS
**Browser:** Chrome, Safari也有该问题

## Actual behaviour 

![image](https://user-images.githubusercontent.com/9602039/84551766-25fc6980-ad41-11ea-925d-5f8bd0d2997c.png)

## Steps to reproduce the behaviour 
个人博客地址：http://lienhui68.gitee.io/
step1 hexo clean && hexo d 部署到gitee上
访问博客，进去首先不显示title图标，接着点击任意链接均没反应，打开控制台显示如图片

**Comment by lienhui68** [comment]
昨天还是一直能访问的， 今天在博客里加了个图片链接，是用gitee作图床，重新部署之后出现的这个问题，但是我删除这个链接重新部署后还是出现此问题。奇怪的是用手机 safari浏览器， 部署前后均没有这个问题。前端知识有限，辛苦yib帮忙排查下。

**Comment by liuyib** [comment]
@lienhui68 您好，我这边访问你的博客没有出现你说的问题，你把有问题的图片链接删除之后，强制刷新下浏览器（Ctrl + F5）应该就没问题了（浏览器缓存导致你重新部署后，问题仍存在）。
至于你说的，加入 gitee 做图床的图片链接后，出现的跨域问题，应该是 https 站中，混用了 http 的链接引起的。

**Comment by lienhui68** [comment]
> @lienhui68 您好，我这边访问你的博客没有出现你说的问题，你把有问题的图片链接删除之后，强制刷新下浏览器（Ctrl + F5）应该就没问题了（浏览器缓存导致你重新部署后，问题仍存在）。
> 至于你说的，加入 gitee 做图床的图片链接后，出现的跨域问题，应该是 https 站中，混用了 http 的链接引起的。

经过多轮测试定位到有问题的地方了，但是不知道为什么。pjax那段配置只要打开就会出现博客中点击链接不跳转的情况，关掉就又好了。

**Comment by lienhui68** [comment]
@liuyib 可以确定就是pjax引起的跨域问题，但是不知道为啥手机和你的电脑可以正常访问，我的电脑上访问就报corx 拦截这种错误

**Comment by liuyib** [comment]
@lienhui68  你是仅仅启用 pjax 就出现跨域的问题了吗？还是配置了其他的项？

**Comment by lienhui68** [comment]
> @lienhui68 你是仅仅启用 pjax 就出现跨域的问题了吗？还是修改了 pjax 其他的配置项？

仅启用就会出现这个情况， pjax其他配置不变。 控制台里报跨域错误也是指向的pjax。

**Comment by lienhui68** [comment]
> @lienhui68 你是仅仅启用 pjax 就出现跨域的问题了吗？还是修改了 pjax 其他的配置项？

我猜测是使用gitee导致的，访问github page页 可能做了一些cors的处理， gitee就没有。 看了下使用stun的博客， gitee的都没有启用拉head功能

**Comment by liuyib** [comment]
那这个问题主题也没法解决了
