### ISSUE TITLE
about picture

### ISSUE THREAD

**Issue by gongdananyou** [liuyib/hexo-theme-stun#85]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [x] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:**  2.0.1

**Hexo Version:** 4.2.1

**Platform:**  windows10

**Browser:** edge chromium

## Expected behaviour 
**I want to insert a picture which not be expanded  in post**
**我想在文章中插入不能被放大的图片**

## Actual behaviour 

**Every picture is default expanded**
**每张图片都默认可以被放大**

## Feature Request 
**Is there has any way to make the picture not be expanded**
**有没有什么途径可以控制图片不被放大**

---

**Comment by liuyib** [comment]
@gongdananyou 默认图片可以放大，这是默认开启的一个功能，你可以在配置文件里关闭，搜索：
```yaml
zoom_image:
  enable: false
```

如果你想要图片可以放大，指定某个图片不允许放大，这个功能还暂不支持。

**Comment by gongdananyou** [comment]
@liuyib 这是我的配置，放大是不能放大了，结果一点就直接转图片链接了，可以变成就单纯展示图片吗
```yml
fancybox: false
zoom_image:
  enable: false
  mask_color: "rgba(0,0,0,0.6)"
  gap_aside: 20px
```

**Comment by liuyib** [comment]
@gongdananyou 关上 `zoom_image` 功能后，就是单纯显示图片。你可以截图让我看下你的效果吗？

**Comment by gongdananyou** [comment]
![微信截图_20200630223505](https://user-images.githubusercontent.com/60178803/86139440-4f2f3f00-bb22-11ea-818f-a83960c2b01f.png)

![微信截图_20200630223518](https://user-images.githubusercontent.com/60178803/86139460-58201080-bb22-11ea-903f-5f4097dd02f7.png)
就这样直接插入图片，然后点击就直接跳转过去了

**Comment by liuyib** [comment]
麻烦你鼠标右键，查看元素，把图片对应的相关 HTML 代码截图发下

**Comment by gongdananyou** [comment]
![微信截图_20200630225842](https://user-images.githubusercontent.com/60178803/86141992-455b0b00-bb25-11ea-8435-876becd2b25f.png)
好像是fancybox的原因，我已经关了fancybox，但是它还会渲染一次，还附带链接

**Comment by liuyib** [comment]
你现在这种点击图片跳转的效果，有两种可能，一是图片外面包了一层<a&gt;标签，二是Linux系统下图片可能都默认可以点击跳转（这个我不确定，麻烦你去其他网站找一些图片验证下）。
你关闭主题提供的放大图片功能后，主题是不会给图片包一层<a&gt;标签的，所以这应该不是主题造成的。具体原因有待考证


 
---Original---

**Comment by liuyib** [comment]
缓存造成的吧，1. 强制刷新下浏览器试试 2. 执行hexo clean 后再执行hexo s 试试。
应该就没问题了


 
---Original---

**Comment by gongdananyou** [comment]
应该不是缓存的问题 我一直都是开的无痕 已经clean过很多次了 还是这样 我觉得可能是fancybox的判断逻辑有点问题

**Comment by liuyib** [comment]
加下q群吧 1019013440，太晚了，我现在身边没电脑，明早在群里讨论吧🤗


 
---Original---
