### ISSUE TITLE
更新时间问题

### ISSUE THREAD

**Issue by sunyubk** [liuyib/hexo-theme-stun#93]
你好，由于我换了电脑进行了迁移，不知道什么时候改了什么东西，现在更新文章，文章头的更新于的时间不变了，这个要怎么办呀

**Comment by liuyib** [comment]
@sunyubk 
- 请确认这是 Stun 主题引起的问题，步骤：1. 更换其他任意主题（例如：默认的 landscape 主题 或 NexT 主题）2. 检查其他主题是否仍存在这个问题。
- 再者，请确认你的新电脑的时间准确无误。

**Comment by sunyubk** [comment]
没有解决这个问题，换回next主题还要设置一些东西，不行弄所以没有弄，现在就在手动改更新时间

**Comment by liuyib** [comment]
@sunyubk  关于文章更新时间，主题只是利用 Hexo Api 获取到，然后通过一定样式显示出来，其具体值并不受主题影响。如你描述的，更新时间不变，这个理论上和主题无关。
