### ISSUE TITLE
sidebar  show have some question

### ISSUE THREAD

**Issue by Whippet0** [liuyib/hexo-theme-stun#97]
## I want to create a new issue 

- [] Yes, I have read [FAQ](https://github.com/liuyib/hexo-theme-stun/blob/master/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/).
- [x] Yes, I have read [Hexo-theme-stun Docs](https://liuyib.github.io/hexo-theme-stun/zh-CN/).
- [] And yes, I already searched for current [issues](https://github.com/liuyib/hexo-theme-stun/issues) and this did not help me.

## Stun Information

**Stun Version:** 

**Hexo Version:** 

**Platform:** 

**Browser:** 

## Feature Request 

---

侧栏显示时仅仅在\languages\zh-CN.yml 中修改显示信息会疯狂的报错
![image](https://user-images.githubusercontent.com/46486374/91642245-6b852480-ea5c-11ea-98b3-529366e1886c.png)
我仅仅是想在后面添加 以变成 你已经阅读20% 这样
![image](https://user-images.githubusercontent.com/46486374/91642270-92435b00-ea5c-11ea-9ecd-339b0a60fa1e.png)
目前显示时这样的 我该如何进行修改

**Comment by liuyib** [comment]
确实忘记在阅读进度的数字后面添加 % 了，这个问题竟然一直没人提出来。。。这个未来的版本会加上，目前暂时的解决办法是：

1. 修改模板文件
`\your hexo root directory\themes\stun\layout\_partials\sidebar\sidebar.pug`
![image](https://user-images.githubusercontent.com/38221479/91676293-f441b480-eb71-11ea-926f-85bc74c3b09f.png)
修改为：
![image](https://user-images.githubusercontent.com/38221479/91676340-15a2a080-eb72-11ea-9eff-be44dfcf511c.png)

2. 修改 JS 文件
`\your hexo root directory\themes\stun\source\js\sidebar.js`
![image](https://user-images.githubusercontent.com/38221479/91676382-3d920400-eb72-11ea-9e29-6fac60048cbc.png)

感谢反馈 🙌

**Comment by liuyib** [comment]
已实现，见：https://github.com/liuyib/hexo-theme-stun/pull/104
